/* ===== Trickle v12 — frames part 3: Savings, Insights, app settings, retention sheets ===== */
var V_SET=[['V-S1','New goal'],['V-S2','Goal order'],['V-S3','Leftover rule']];
function goalSegs(g){return [{amt:g.saved,c:'sv',st:'solid',name:'Saved'},{amt:Math.max(0,g.target-g.saved),c:'sv',st:'out',name:'To go'}];}
function monthsSav(){return monthKeys().map(function(k){var mo=+k.slice(5)-1,s=0;L.goals.forEach(function(g){g.contribs.forEach(function(c){if(c.ts.m===mo&&c.amt>0)s+=c.amt;});});L.genLog.forEach(function(c){if(c.ts.m===mo&&c.amt>0)s+=c.amt;});return {mo:mo,amt:s};});}
F('V-01',{tab:'V',kind:'tab',title:'Savings',r:function(){var g=L.goals.filter(function(g){return !g.reachedTs;})[0]||L.goals[0];var e=goalEta(g);
  var start=4,end=12+0;var fr=(L.today.m-start+L.today.d/31)/(end-start+1);
  return hd('Savings',{help:'V-00',gear:'V-S2'})+'<main class="scr"><button class="card tile" data-go="V-03" data-ctx=\'{"g":"'+g.id+'"}\' aria-label="'+esc(g.name)+'"><p class="eyb">Goal</p><p class="lead">'+esc(g.name)+'</p>'+dots(goalSegs(g),{zoomable:false})+'<p class="legend"><span>'+dot1('sv','solid')+' saved</span><span>'+dot1('sv','out')+' to go</span></p></button>'+
  '<section class="card"><p class="eyb">When it fills</p><p class="lead">'+(e.months?'Around '+MONL[(L.today.m+e.months)%12]:'Ready now')+'</p>'+glowTrack(fr,{n:28,label:'From May to the goal month',marks:[{f:Math.min(1,(L.today.m+e.months-start+0.5)/(end-start+1))}]})+'<p class="sub">The glow is today. The line is when '+esc(g.name)+' fills at this pace, '+(g.by?'ahead of '+esc(g.by.split(' ')[0]):'')+'.</p></section>'+
  (function(){var ms=monthsSav(),out='';for(var i=0;i<ms.length;i+=3){var ch=ms.slice(i,i+3);out+='<section class="card"><p class="eyb">Growth by month · '+MON[ch[0].mo]+'–'+MON[ch[ch.length-1].mo]+'</p>'+ch.map(function(x){return '<div class="lane"><span class="lb">'+MON[x.mo]+'</span><span class="bar">'+dots([{amt:x.amt,c:'sv',st:'solid',name:'Saved in '+MON[x.mo]}],{size:'widget',cols:22})+'</span></div>';}).join('')+'</section>';}return out;})()+
  '<section class="card"><p class="eyb">Leftover rolled in</p>'+dots(monthKeys().filter(function(k){var m=L.months[k];return m.closed&&m.leftover&&m.leftover.to==='savings'&&m.leftover.amt;}).map(function(k){return {amt:L.months[k].leftover.amt,c:'sv',st:'solid',name:'Saved from '+MONL[+k.slice(5)-1]};}),{})+'<p class="sub">What was left at month-end went to savings</p></section>'+
  key()+'<button class="link" data-go="V-02" style="align-self:center">All goals</button></main>';}});
F('V-02',{tab:'V',kind:'push',title:'All goals',r:function(){return hd('All goals',{back:1})+'<main class="scr">'+L.goals.map(function(g){return '<button class="card tile" data-go="V-03" data-ctx=\'{"g":"'+g.id+'"}\'><p class="lead">'+esc(g.name)+'</p>'+dots(goalSegs(g),{zoomable:false})+'<p class="sub">'+(g.reachedTs?'Complete':'By '+esc(g.by||'any time'))+'</p></button>';}).join('')+
  '<section class="card"><p class="eyb">General savings</p>'+dots([{amt:L.general,c:'sv',st:'solid',name:'General'}])+'<p class="sub">Not tied to a goal</p></section>'+btn('New goal','',{go:'V-S1'})+key()+'</main>';}});
F('V-03',{tab:'V',kind:'push',title:'Goal',r:function(){var g=L.goals.filter(function(x){return x.id===S.ctx.g;})[0]||L.goals[0];
  return hd(esc(g.name),{back:1})+'<main class="scr"><section class="card">'+dots(goalSegs(g))+'<p class="legend"><span>'+dot1('sv','solid')+' saved</span><span>'+dot1('sv','out')+' to go</span></p></section>'+
  '<p class="eyb">Add to it</p><div class="chips" role="group" aria-label="Add to goal"><button class="chip" data-a="gadd" data-v="100" data-ctx=\'{"g":"'+g.id+'"}\'>Add ₹100</button><button class="chip" data-a="gadd" data-v="500" data-ctx=\'{"g":"'+g.id+'"}\'>Add ₹500</button></div>'+
  '<button class="link" data-go="R-06" data-ctx=\'{"g":"'+g.id+'"}\'>Take money out</button>'+key()+
  '<p class="eyb">Contributions</p><div class="card list">'+g.contribs.slice().reverse().slice(0,10).map(function(c){return '<div class="li"><span class="t"><b>'+({split:'From a split',leftover:'Month-end leftover',add:'Added by you',withdraw:'Taken out',use:'Used at pay'}[c.src]||c.src)+'</b><small>'+dd(c.ts.d||1,c.ts.m)+'</small></span><span class="amt">'+inr(c.amt)+'</span></div>';}).join('')+'</div></main>';}});
F('V-04',{tab:'V',kind:'push',title:'Goal complete',r:function(){var g=L.goals.filter(function(x){return x.reachedTs;})[0]||L.goals[0];var C=2*Math.PI*70;var f=g.reachedTs?1:Math.min(1,g.saved/g.target);
  return hd('',{back:1})+'<main class="scr" style="align-items:center;text-align:center"><svg class="bangle" viewBox="0 0 180 180" width="200" height="200" role="img" aria-label="Goal ring '+(g.reachedTs?'closed':'still open')+'"><circle class="bg" cx="90" cy="90" r="70"/><circle class="fg" cx="90" cy="90" r="70" stroke-dasharray="'+C.toFixed(1)+'" stroke-dashoffset="'+(C*(1-f)).toFixed(1)+'" transform="rotate(-90 90 90)"/></svg>'+
  '<h2 class="lead">'+(g.reachedTs?esc(g.name)+' is complete':esc(g.name)+' closes like this when it fills')+'</h2><p class="muted">'+(g.reachedTs?'Every green dot is in. Spend it on the thing you saved for.':'The ring closes the moment the last dot lands.')+'</p></main>';},after:function(){fx('goal.bangle',document.querySelector('.bangle'));}});
F('V-S1',{tab:'V',kind:'push',title:'New goal',r:function(){var c=S.ctx,st=c.step||1;var h=hd('New goal',{back:1})+'<main class="scr"><div class="prog" aria-hidden="true"><i class="on"></i><i'+(st>1?' class="on"':'')+'></i><i'+(st>2?' class="on"':'')+'></i></div>';
  if(st===1)return h+'<p class="lead">What are you saving for?</p><div class="choice">'+['Laptop','Trip home','Concert','Course fee'].map(function(n){return '<button class="opt" data-a="ng1" data-v="'+n+'"><span class="grow"><b>'+n+'</b></span>'+ic('chev','')+'</button>';}).join('')+'</div><label class="sr" for="gname">Goal name</label><input class="inp" id="gname" placeholder="Or type a name"><button class="btn block" data-a="ng1t">Next</button></main>';
  if(st===2)return h+'<p class="lead">How much for '+esc(c.name)+'?</p><div class="choice">'+[2000,5000,20000,40000].map(function(a){return '<button class="opt" data-a="ng2" data-v="'+a+'"><span class="grow"><b>'+inr(a)+'</b></span></button>';}).join('')+'</div></main>';
  return h+'<p class="lead">By when?</p>'+dots([{amt:c.amt,c:'sv',st:'out',name:'To go'}])+'<div class="choice">'+['Dec 2026','Mar 2027','Jun 2027','No date'].map(function(b){return '<button class="opt" data-a="ng3" data-v="'+b+'"><span class="grow"><b>'+b+'</b></span></button>';}).join('')+'</div>'+key()+'</main>';}});
F('V-S2',{tab:'V',kind:'push',title:'Goal order',r:function(){return hd('Goal order',{back:1})+'<main class="scr"><p class="muted">Savings fill the top goal first.</p><div class="card list">'+L.goals.map(function(g,i){return '<div class="li"><span class="t"><b>'+esc(g.name)+'</b><small>'+(i===0?'Fills first':'Then')+'</small></span><button class="ib" data-a="gup" data-v="'+g.id+'" aria-label="Move '+esc(g.name)+' up">'+ic('up')+'</button></div>';}).join('')+'</div>'+setLinks([V_SET[0],V_SET[2]])+'</main>';}});
F('V-S3',{tab:'V',kind:'push',title:'Leftover rule',r:function(){var r=L.prefs.leftoverRule;return hd('Leftover rule',{back:1})+'<main class="scr"><p class="muted">At month-end Trickle asks once. This is the answer it suggests.</p><div class="choice" role="radiogroup">'+[['savings','Move to Savings','Default'],['next','Keep for next month','Tops up next month’s jars']].map(function(o){return '<button class="opt'+(r===o[0]?' def':'')+'" role="radio" aria-checked="'+(r===o[0])+'" data-a="lrule" data-v="'+o[0]+'"><span class="grow"><b>'+o[1]+'</b><small>'+o[2]+'</small></span></button>';}).join('')+'</div>'+setLinks(V_SET.slice(0,2))+'</main>';}});

/* ---------- Insights ---------- */
var LIB=[{id:'drift',name:'Category drift'},{id:'places',name:'Top places'},{id:'tod',name:'Time of day'},{id:'wday',name:'Weekday pattern'},{id:'cal',name:'Calendar'},{id:'range',name:'Spend range'},{id:'big',name:'Big one-offs'},{id:'subyear',name:'Subscription yearly cost'},{id:'flow',name:'Money flow'},{id:'rate',name:'Savings rate'},{id:'time',name:'Money as time'},{id:'mbm',name:'Month by month'}];
var BOARD={changed:'What changed',share:'Category share',small:'Small buys add up',story:'Month story'};
function insCard(id){var m=cur();
 if(id==='changed'){var tw=weekSpend(0),lw=weekSpend(1),ex=tw-lw;return '<section class="card" aria-label="What changed"><p class="eyb">What changed</p><p class="lead">'+(ex>0?'This week ran fuller than last':'This week was lighter than last')+'</p>'+
   dots([{amt:Math.min(tw,lw),c:'ink',st:'out',name:'This week'}].concat(ex>0?[{amt:ex,c:'ink',st:'hatch',name:'Beyond last week'}]:[{amt:-ex,c:'ink',st:'ghost',name:'Last week, not used this week'}]))+'<p class="legend"><span>'+dot1('ink','out')+' this week</span><span>'+(ex>0?dot1('ink','hatch')+' beyond last week':dot1('ink','ghost')+' last week')+'</span></p><p class="sub">The dinner at Saravana Bhavan is most of the change.</p></section>';}
 if(id==='share'){return '<section class="card" aria-label="Category share"><p class="eyb">Where it went</p>'+dots(jarNames().map(function(j){return {amt:jarSpent(j),c:jcls(j),st:'out',name:j};}))+'<p class="legend">'+jarNames().map(function(j){return '<span>'+jsw(j)+j+'</span>';}).join('')+'</p></section>';}
 if(id==='small'){var sb=smallBuys().reduce(function(a,x){return a+x.amt;},0),eq=equivalent(sb);return '<section class="card" aria-label="Small buys"><p class="eyb">Small buys add up</p>'+dots([{amt:sb,c:'ink',st:'out',name:'Small buys'}])+'<p class="sub">Every buy under a dot, together. That is about '+wn(Math.min(eq.n,12))+(eq.n>12?' dozen':'')+' of your '+eq.what+'.</p></section>';}
 if(id==='story'){var pm=(L.today.m+11)%12;return '<button class="card tile" data-go="N-04" aria-label="Month story"><p class="eyb">Month story</p><p class="lead">'+MONL[pm]+' in five cards</p><p class="sub">Big buy, little things, where it went, what changed, and what you kept.</p></button>';}
 var lb=LIB.filter(function(l){return l.id===id;})[0];return lb?'<button class="card tile" data-go="N-03" data-ctx=\'{"id":"'+id+'"}\'><p class="eyb">Pinned</p><p class="lead">'+lb.name+'</p></button>':'';}
F('N-01',{tab:'N',kind:'tab',title:'Insights',r:function(){var pins=L.prefs.insightsPins;return hd('Insights',{help:'N-00',gear:'N-S1'})+'<main class="scr">'+pins.map(insCard).join('')+key()+btn('Open the library','',{go:'N-02'})+'<button class="link" data-go="N-05" style="align-self:center">This week’s check-in</button></main>';}});
F('N-02',{tab:'N',kind:'push',title:'Library',r:function(){return hd('Library',{back:1})+'<main class="scr"><p class="muted">Twelve more ways to look. Pin any to your Insights board.</p><div class="card list">'+LIB.map(function(l){var p=L.prefs.insightsPins.indexOf(l.id)>=0;return '<div class="li"><button class="t" style="text-align:left;min-height:44px" data-go="N-03" data-ctx=\'{"id":"'+l.id+'"}\'><b>'+l.name+'</b></button><button class="chip" data-a="pin" data-v="'+l.id+'" aria-pressed="'+p+'">'+(p?'Pinned':'Pin')+'</button></div>';}).join('')+'</div></main>';}});
function libView(id){var m=cur(),ks=monthKeys();
 if(id==='drift'){var j=S.ctx.j||'Food';return '<div class="chips" role="group">'+jarNames().map(function(x){return '<button class="chip" data-go="N-03" data-ctx=\'{"id":"drift","j":"'+x+'"}\' aria-pressed="'+(x===j)+'">'+x+'</button>';}).join('')+'</div><section class="card">'+ks.map(function(k){var mm=L.months[k];return '<div class="lane"><span class="lb">'+MON[+k.slice(5)-1]+'</span><span class="bar">'+dots([{amt:jarSpent(j,mm),c:jcls(j),st:'out',name:j}],{size:'widget',cols:22})+'</span></div>';}).join('')+'</section><p class="sub">'+j+' spending, month by month. October is part way through.</p>';}
 if(id==='places'){var c={};m.spends.forEach(function(x){c[x.payee]=(c[x.payee]||0)+x.amt;});var top=Object.keys(c).sort(function(a,b){return c[b]-c[a];}).slice(0,4);return '<section class="card">'+top.map(function(p){return '<p class="small">'+esc(p)+'</p>'+dots([{amt:c[p],c:'ink',st:'out',name:p}],{size:'widget',cols:22});}).join('')+'</section>';}
 if(id==='tod'){var h=new Array(24).fill(0);ks.forEach(function(k){L.months[k].spends.forEach(function(x){h[x.hour]++;});});var mx=Math.max.apply(null,h);
   return '<section class="card"><svg class="glow" viewBox="0 0 240 40" width="100%" height="60" role="img" aria-label="Spending by hour of day">'+h.map(function(v,i){return '<circle class="gd'+(v>mx*0.6?' now':v?' lit':'')+'" cx="'+(i*10+5)+'" cy="18" r="'+(1.5+3*v/mx).toFixed(1)+'"/>';}).join('')+'<text x="5" y="38" font-size="7" fill="currentColor">Morning</text><text x="120" y="38" font-size="7" fill="currentColor" text-anchor="middle">Afternoon</text><text x="235" y="38" font-size="7" fill="currentColor" text-anchor="end">Night</text></svg><p class="sub">Brighter means more buys at that hour. Evenings glow the most.</p></section>';}
 if(id==='wday'){var w=[0,0,0,0,0,0,0];m.spends.forEach(function(x){w[(new Date(2026,9,x.day).getDay()+6)%7]+=x.amt;});return '<section class="card">'+['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(function(d,i){return '<div class="lane"><span class="lb">'+d+'</span><span class="bar">'+dots([{amt:w[i],c:'ink',st:'out',name:d}],{size:'widget',cols:22})+'</span></div>';}).join('')+'</section>';}
 if(id==='cal'){var D=dim(2026,9),d0=(new Date(2026,9,1).getDay()+6)%7,cells='';var t={};m.spends.forEach(function(x){t[x.day]=(t[x.day]||0)+x.amt;});
   for(var i=0;i<d0+D;i++){var d=i-d0+1;cells+='<span style="aspect-ratio:1;border-radius:50%;display:grid;place-items:center" aria-label="'+(d>0?'Day '+d:'')+'">'+(d>0?'<i style="width:'+(d>L.today.d?4:Math.min(26,6+((t[d]||0)/40)))+'px;height:'+(d>L.today.d?4:Math.min(26,6+((t[d]||0)/40)))+'px;border-radius:50%;background:'+(d===L.today.d?'var(--glow)':d>L.today.d?'var(--line)':'var(--ink3)')+';'+(d===L.today.d?'box-shadow:0 0 10px var(--glow)':'')+'"></i>':'')+'</span>';}
   return '<section class="card"><div style="display:grid;grid-template-columns:repeat(7,1fr);gap:4px" role="img" aria-label="October calendar, bigger circle means more spent">'+cells+'</div><p class="sub">Bigger circles are fuller days. The glowing one is today.</p></section>';}
 if(id==='range'){var a=m.spends.map(function(x){return x.amt;}).sort(function(a,b){return a-b;});return '<section class="card"><p class="small">Smallest</p>'+dots([{amt:a[0],c:'ink',st:'out'}],{size:'widget'})+'<p class="small">Typical</p>'+dots([{amt:a[Math.floor(a.length/2)],c:'ink',st:'out'}],{size:'widget'})+'<p class="small">Largest</p>'+dots([{amt:a[a.length-1],c:'ink',st:'out'}],{size:'widget'})+'</section>';}
 if(id==='big'){var b=m.spends.filter(function(x){return x.amt>=400;});return '<section class="card">'+b.map(function(x){return '<p class="small">'+esc(x.payee)+'</p>'+dots([{amt:x.amt,c:jcls(x.jar),st:'out',name:x.payee}],{size:'widget'});}).join('')+'</section><p class="sub">Spends of four dots or more this month.</p>';}
 if(id==='subyear'){return '<section class="card">'+liveSubs(m).map(function(s){return '<p class="small">'+esc(s.name)+' · a year</p>'+dots([{amt:s.amt*12,c:'inc',st:'held',name:s.name}],{size:'widget'});}).join('')+'</section>';}
 if(id==='flow')return sankey(S.ctx.alt);
 if(id==='rate'){return '<section class="card">'+ks.map(function(k){var mm=L.months[k];return '<div class="lane"><span class="lb">'+MON[+k.slice(5)-1]+'</span><span class="bar">'+dots([{amt:mm.savingsSplit+(mm.leftover&&mm.leftover.to==='savings'?mm.leftover.amt:0),c:'sv',st:'solid',name:'Saved'}],{size:'widget',cols:22})+'</span></div>';}).join('')+'</section><p class="sub">Green kept each month, from splits and leftovers.</p>';}
 if(id==='time'){return '<section class="card">'+jarNames().map(function(j){var d=daySpread(j)?Math.floor(left(j)/Math.max(1,Math.floor(jarSpent(j)/L.today.d))):0;return '<p class="small">'+j+' lasts about '+wn(Math.min(d,12))+(d>12?' plus':'')+' more days at this pace</p>'+glowTrack(Math.min(1,d/daysLeft()),{n:18,w:200,label:j+' days'});}).join('')+'</section>';}
 if(id==='mbm'){return '<section class="card">'+ks.map(function(k){var mm=L.months[k];return '<div class="lane"><span class="lb">'+MON[+k.slice(5)-1]+'</span><span class="bar">'+dots([{amt:spentAll(mm),c:'ink',st:'out',name:'Spent'}],{size:'widget',cols:22})+'</span></div>';}).join('')+'</section>';}
 return '';}
function sankey(alt){var m=cur(),inc=m.incomes.reduce(function(a,i){return a+(i.intent==='split'?i.amt:0);},0),sv=m.savingsSplit,sub=subsTotal(),jars=jarNames();
 if(alt)return '<section class="card"><div class="row"><div class="grow"><p class="eyb">In</p>'+dots([{amt:inc,c:'inc',st:'solid',name:'Came in'}],{size:'widget'})+'</div><div class="grow"><p class="eyb">Out</p>'+dots([{amt:sv,c:'sv',st:'solid',name:'Savings'}].concat(jars.map(function(j){return {amt:jarSpent(j),c:jcls(j),st:'out',name:j};})),{size:'widget'})+'</div></div></section><button class="link" data-go="N-03" data-ctx=\'{"id":"flow"}\'>Show as ribbons</button>';
 var H=240,k=H/inc,y=0,rows=[];var tg=[{n:'Savings',a:sv,c:'sv',st:'solid'},{n:'Subscriptions',a:sub,c:'inc',st:'held'}].concat(jars.map(function(j){return {n:j,a:m.jars[j].budget,c:jcls(j),st:'solid'};}));
 var ty=0,gap=6;var out='<svg viewBox="0 0 320 '+(H+gap*tg.length+10)+'" width="100%" role="img" aria-label="Money flow from income to savings, subscriptions and jars">';
 out+='<rect x="0" y="0" width="14" height="'+(H)+'" rx="4" class="m solid inc"/>';
 tg.forEach(function(t){var h=t.a*k;var y1=y,y2=ty;var p='M14 '+y1.toFixed(1)+' C120 '+y1.toFixed(1)+' 140 '+y2.toFixed(1)+' 230 '+y2.toFixed(1)+' L230 '+(y2+h).toFixed(1)+' C140 '+(y2+h).toFixed(1)+' 120 '+(y1+h).toFixed(1)+' 14 '+(y1+h).toFixed(1)+'Z';
   out+='<path d="'+p+'" class="m '+t.c+' '+(t.st==='solid'?'solid':'held')+'" style="opacity:.35"/>';
   var sp=t.n===('Savings')?0:t.n==='Subscriptions'?subsPaid():jarSpent(t.n);var sh=Math.min(h,sp*k);
   out+='<rect x="232" y="'+y2.toFixed(1)+'" width="14" height="'+Math.max(1,h).toFixed(1)+'" rx="3" class="m '+t.c+' '+(t.st==='held'?'held':'solid')+'"/>';
   if(sh>0)out+='<rect x="232.8" y="'+(y2+h-sh+.8).toFixed(1)+'" width="12.4" height="'+Math.max(0.5,sh-1.6).toFixed(1)+'" rx="3" class="m '+t.c+' out" style="fill:var(--card)"/>';
   out+='<text x="252" y="'+(y2+h/2+4).toFixed(1)+'" font-size="11" fill="currentColor">'+t.n+'</text>';y+=h;ty+=h+gap;});
 return '<section class="card" style="color:var(--ink2)">'+out+'</svg><p class="legend"><span>'+dot1('ink','solid')+' left</span><span>'+dot1('ink','out')+' spent</span><span>'+dot1('inc','held')+' held</span></p><p class="sub">This month’s allowance on the true scale, flowing into savings first, then subscriptions and jars.</p></section><button class="link" data-go="N-03" data-ctx=\'{"id":"flow","alt":1}\'>Show as two columns</button>';}
F('N-03',{tab:'N',kind:'push',title:'Library view',r:function(){var id=S.ctx.id||'flow';var lb=LIB.filter(function(l){return l.id===id;})[0];var p=L.prefs.insightsPins.indexOf(id)>=0;
  return hd(lb.name,{back:1})+'<main class="scr">'+libView(id)+key()+'<button class="btn block" data-a="pin" data-v="'+id+'">'+(p?'Unpin from Insights':'Pin to Insights')+'</button></main>';}});
function storyCards(){var pk=prevKey()||curKey(),pm=L.months[pk],mo=+pk.slice(5)-1;var big=pm.spends.slice().sort(function(a,b){return b.amt-a.amt;})[0];var sb=smallBuys(pm).reduce(function(a,x){return a+x.amt;},0);var ppk=prevKey(pk),pp=ppk?L.months[ppk]:null;
 var kept=pm.leftover?pm.leftover.amt:0;
 return [{h:'The big buy',b:big?esc(big.payee):'',v:dots([{amt:big?big.amt:0,c:jcls(big.jar,pm),st:'out',name:'Big buy'}],{size:'hero'})},
  {h:'Little things',b:'Every buy under a dot, together',v:dots([{amt:sb,c:'ink',st:'out',name:'Little things'}],{size:'hero'})},
  {h:'Where it went',b:Object.keys(pm.jars).join(' · '),v:dots(Object.keys(pm.jars).map(function(j){return {amt:jarSpent(j,pm),c:pm.jars[j].c,st:'out',name:j};}),{size:'card'})},
  {h:'What changed',b:pp?(spentAll(pm)>spentAll(pp)?'A little fuller than '+MONL[mo-1]:'Lighter than '+MONL[mo-1]):'',v:pp?dots([{amt:Math.min(spentAll(pm),spentAll(pp)),c:'ink',st:'out',name:MONL[mo]},{amt:Math.abs(spentAll(pm)-spentAll(pp)),c:'ink',st:spentAll(pm)>spentAll(pp)?'hatch':'ghost',name:'Difference'}]):''},
  {h:'You kept '+inr(kept),b:'It went to savings',v:dots([{amt:kept,c:'sv',st:'solid',name:'Kept'}],{size:'hero'}),last:1}];}
F('N-04',{tab:'N',kind:'push',title:'Month story',r:function(){var i=S.ctx.i||0,c=storyCards(),x=c[i];var mo=+(prevKey()||curKey()).slice(5)-1;
  return hd(MONL[mo]+' story',{back:1})+'<main class="scr"><div class="prog" aria-label="Card '+(i+1)+' of five">'+c.map(function(_,k){return '<i'+(k<=i?' class="on"':'')+'></i>';}).join('')+'</div><section class="card story" aria-live="polite"><p class="lead">'+x.h+'</p>'+x.v+'<p class="sub">'+x.b+'</p></section>'+key()+
  '<div class="row">'+(i>0?'<button class="btn" data-go="N-04" data-ctx=\'{"i":'+(i-1)+'}\'>Back</button>':'')+'<span class="grow"></span>'+(x.last?btn('Make a share poster','',{go:'N-04s',primary:true,block:false}):btn('Next','',{go:'N-04',primary:true,block:false}).replace('data-go="N-04"','data-go="N-04" data-ctx=\'{"i":'+(i+1)+'}\''))+'</div></main>';},after:function(){fx('story.frame',document.querySelector('.story'));}});
F('N-04s',{tab:'N',kind:'push',title:'Share poster',exempt:1,r:function(){var show=!!S.ctx.show;var pk=prevKey()||curKey(),pm=L.months[pk],mo=+pk.slice(5)-1;
  return hd('Share poster',{back:1})+'<main class="scr"><div class="poster" role="img" aria-label="Poster for '+MONL[mo]+'"><p style="font-weight:700;letter-spacing:-.04em;font-size:20px;margin:0">Trickle</p><p class="lead" style="color:#f4f4f5">My '+MONL[mo]+'</p>'+
  dots(Object.keys(pm.jars).map(function(j){return {amt:jarSpent(j,pm),c:pm.jars[j].c,st:'out',name:j};}).concat([{amt:pm.leftover?pm.leftover.amt:0,c:'sv',st:'solid',name:'Kept'}]),{zoomable:false})+
  '<p style="color:#b4b4ba;font-size:13px;margin:0">'+(show?'Kept '+inr(pm.leftover?pm.leftover.amt:0)+' · spent '+inr(spentAll(pm)):'Green is what I kept')+'</p></div>'+
  '<div class="row"><span class="grow">Show amounts</span><button class="tog" role="switch" aria-checked="'+show+'" data-go="N-04s" data-ctx=\'{"show":'+(!show)+'}\' aria-label="Show amounts on poster"></button></div>'+btn('Share poster','share',{primary:true})+'</main>';}});
F('N-05',{tab:'N',kind:'sheet',base:'N-01',title:'Weekly check-in',r:function(){var tw=weekSpend(0),lw=weekSpend(1);return '<p class="eyb">Weekly check-in</p><h2>'+(tw>lw?'A fuller week, mostly one dinner out':'A calm week')+'</h2>'+
  dots([{amt:Math.min(tw,lw),c:'ink',st:'out',name:'This week'},{amt:Math.abs(tw-lw),c:'ink',st:tw>lw?'hatch':'ghost',name:tw>lw?'Beyond last week':'Last week'}],{zoomable:false})+'<p class="muted small">The days ahead have already re-spread. Nothing to fix.</p>'+key()+btn('Start the new week','checkin',{primary:true});},after:function(){fx('week.fresh');}});
F('N-S1',{tab:'N',kind:'push',title:'Pin and hide cards',r:function(){var p=L.prefs.insightsPins;var all=Object.keys(BOARD).map(function(k){return [k,BOARD[k]];}).concat(LIB.map(function(l){return [l.id,l.name];}));
  return hd('Cards',{back:1})+'<main class="scr"><div class="card list">'+all.map(function(x){var on=p.indexOf(x[0])>=0;return '<div class="li"><span class="t"><b>'+x[1]+'</b></span><button class="tog" role="switch" aria-checked="'+on+'" data-a="pin" data-v="'+x[0]+'" aria-label="Show '+x[1]+'"></button></div>';}).join('')+'</div>'+setLinks([['N-S2','Check-in day and time']])+'</main>';}});
F('N-S2',{tab:'N',kind:'push',title:'Check-in day',r:function(){var c=L.prefs.checkin;return hd('Check-in',{back:1})+'<main class="scr"><p class="eyb">Day</p><div class="chips" role="radiogroup" aria-label="Day">'+['Sun','Mon','Fri','Sat'].map(function(d){var i=DOW.indexOf(d);return '<button class="chip" role="radio" data-a="cday" data-v="'+i+'" aria-checked="'+(c.dow===i)+'" aria-pressed="'+(c.dow===i)+'">'+d+'</button>';}).join('')+'</div>'+
  '<p class="eyb">Time</p><div class="chips" role="radiogroup" aria-label="Time">'+[['09:00','Morning'],['13:00','Afternoon'],['19:30','Evening']].map(function(t){return '<button class="chip" role="radio" data-a="ctime" data-v="'+t[0]+'" aria-checked="'+(c.time===t[0])+'" aria-pressed="'+(c.time===t[0])+'">'+t[1]+'</button>';}).join('')+'</div><p class="small muted">Never between ten at night and eight in the morning.</p></main>';}});

/* ---------- app-wide settings (avatar) ---------- */
var G_SET=[['G-S1','Look'],['G-S2','Linked UPI IDs'],['G-S3','Notifications'],['G-S4','Sounds and motion'],['G-S5','App lock'],['G-S6','Data and export']];
function gl(id){return setLinks(G_SET.filter(function(x){return x[0]!==id;}));}
function opts(k,list,label){return '<div class="chips" role="radiogroup" aria-label="'+label+'">'+list.map(function(o){var on=L.prefs[k]===o[0];return '<button class="chip" role="radio" aria-checked="'+on+'" aria-pressed="'+on+'" data-a="pref" data-v="'+o[0]+'" data-ctx=\'{"k":"'+k+'"}\'>'+o[1]+'</button>';}).join('')+'</div>';}
F('G-S1',{tab:'H',kind:'push',title:'Look',r:function(){return hd('Look',{back:1})+'<main class="scr"><p class="eyb">Colour</p>'+opts('look',[['colour','Colour'],['bw','Black and white']],'Colour')+
  '<p class="eyb">Appearance</p>'+opts('mode',[['system','Follow phone'],['dark','Dark'],['light','Light']],'Appearance')+'<section class="card">'+dots([{amt:600,c:'j0',st:'solid',name:'Food'},{amt:300,c:'j1',st:'solid',name:'Travel'},{amt:300,c:'j2',st:'solid',name:'Fun'},{amt:300,c:'sv',st:'solid',name:'Savings'}],{zoomable:false})+'<p class="sub">Black and white keeps jars apart with patterns and names.</p></section>'+gl('G-S1')+'</main>';}});
F('G-S2',{tab:'H',kind:'push',title:'Linked UPI IDs',r:function(){return hd('Linked UPI IDs',{back:1})+'<main class="scr"><p class="muted">Trickle only sees payments made from linked IDs. You can also add every spend by hand.</p><div class="card list">'+L.upiIds.map(function(u){return '<div class="li"><span class="t"><b>'+esc(u.app)+'</b><small>'+esc(u.id)+'</small></span><button class="tog" role="switch" aria-checked="'+u.linked+'" data-a="upitog" data-v="'+esc(u.id)+'" aria-label="Link '+esc(u.id)+'"></button></div>';}).join('')+'</div>'+
  '<label class="sr" for="newupi">Add UPI ID</label><input class="inp" id="newupi" placeholder="name@bank"><button class="btn block" data-a="upiadd">Link this ID</button>'+(L.manualOnly?'<p class="small muted">Manual only: log spends with the Pay button.</p>':'')+gl('G-S2')+'</main>';}});
var NCH=[['income','Money arrived','Split it'],['subTomorrow','Subscription due tomorrow','See it'],['checkin','Weekly check-in','Start the new week'],['story','Month story','Read it'],['welcome','Welcome back','Start from today']];
F('G-S3',{tab:'H',kind:'push',title:'Notifications',r:function(){var ch=L.notif.channels;return hd('Notifications',{back:1})+'<main class="scr"><p class="muted">At most one a day and three a week. None between ten at night and eight in the morning.</p><div class="card list">'+NCH.map(function(c){return '<div class="li"><span class="t"><b>'+c[1]+'</b><small>Action: '+c[2]+'</small></span><button class="tog" role="switch" aria-checked="'+!!ch[c[0]]+'" data-a="nch" data-v="'+c[0]+'" aria-label="'+c[1]+'"></button></div>';}).join('')+'</div>'+btn('Preview the notification shade','',{go:'R-07'})+gl('G-S3')+'</main>';}});
F('G-S4',{tab:'H',kind:'push',title:'Sounds and motion',r:function(){function tg(k,t,sub){return '<div class="li"><span class="t"><b>'+t+'</b><small>'+sub+'</small></span><button class="tog" role="switch" aria-checked="'+(L.prefs[k]!==false&&!!L.prefs[k])+'" data-a="ptog" data-v="'+k+'" aria-label="'+t+'"></button></div>';}
  return hd('Sounds and motion',{back:1})+'<main class="scr"><div class="card list">'+tg('sound','Sounds','Soft coin when money leaves, chimes for good news, quiet clicks for taps')+tg('haptics','Haptics','A light tick at pay, crumbs, milestones and presses')+tg('silent','Phone on silent (demo)','On silent Trickle makes no sound; haptics still work')+'</div>'+
  '<p class="eyb">Motion</p>'+opts('motion',[['system','Follow phone'],['reduce','Reduce'],['full','Full']],'Motion')+'<p class="small muted">Reduce shows every change at its end state, with no movement. '+(window.matchMedia&&matchMedia('(prefers-reduced-motion: reduce)').matches?'Your phone asks for reduced motion.':'Your phone allows motion.')+'</p>'+gl('G-S4')+'</main>';}});
F('G-S5',{tab:'H',kind:'push',title:'App lock',r:function(){return hd('App lock',{back:1})+'<main class="scr"><div class="card list"><div class="li"><span class="t"><b>Lock with fingerprint or PIN</b><small>Asked when Trickle opens</small></span><button class="tog" role="switch" aria-checked="'+!!L.prefs.lock+'" data-a="ptog" data-v="lock" aria-label="App lock"></button></div></div>'+gl('G-S5')+'</main>';}});
F('G-S6',{tab:'H',kind:'push',title:'Data and export',r:function(){return hd('Data and export',{back:1})+'<main class="scr"><p class="muted">Your data stays on this phone in the prototype.</p>'+btn('Copy this month as CSV','csv',{})+(S.ctx.csv?'<pre class="card small" style="white-space:pre-wrap;overflow-x:auto;margin:0">'+esc(S.ctx.csv)+'</pre>':'')+btn('Start again from the demo month','reset',{})+gl('G-S6')+setLinks([['S-S7','Import a statement']])+'</main>';}});

/* ---------- retention + system sheets ---------- */
F('R-01',{tab:'H',kind:'full',title:'Welcome back',r:function(){var auto=cur().spends.filter(function(x){return x.auto;}).length||3;return zt({g:'fresh',cls:'tall',h:'Your savings<br><em>kept growing</em>',vis:dots([{amt:savingsTotal(),c:'sv',st:'solid',name:'Savings'}],{size:'hero'})+key(),sub:auto+' payments were sorted for you while you were away. You can check them in the bell any time.',foot:zbtn('Start from today','welcome')});}});
F('R-02',{tab:'V',kind:'sheet',base:'V-01',title:'Month-end',r:function(){var amt=leftAll();var r=L.prefs.leftoverRule;return '<p class="eyb">'+MONL[L.today.m]+' is ending</p><h2>'+inr(amt)+' is left over.</h2>'+dots([{amt:amt,c:'inc',st:'solid',name:'Left over'}],{zoomable:false})+key()+
  '<div class="choice" role="group" aria-label="Where should it go"><button class="opt'+(r==='savings'?' def':'')+'" data-a="mend" data-v="savings"><span class="grow"><b>Move to Savings</b><small>'+(r==='savings'?'Suggested':'')+'</small></span></button><button class="opt'+(r==='next'?' def':'')+'" data-a="mend" data-v="next"><span class="grow"><b>Keep for next month</b><small>Tops up next month’s jars</small></span></button></div><p class="small muted">Your month story waits in Insights.</p>';}});
F('R-03',{tab:'S',kind:'sheet',base:'S-01',title:'Refund',r:function(){var n=L.needs.filter(function(n){return n.kind==='refund';})[0];var x=n&&findSpend(n.ref);if(!x)return '<h2>No refunds waiting</h2>'+btn('Close','back',{primary:true});
  return '<p class="eyb">Refund</p><h2>'+inr(x.refundPending)+' back from '+esc(x.payee)+'. Return it to '+x.jar+'?</h2>'+dots([{amt:x.refundPending,c:jcls(x.jar),st:'out',name:'Coming back'}],{zoomable:false})+'<p class="small muted">The outlined dots fill in again.</p>'+key()+btn('Return to '+x.jar,'refund',{primary:true}).replace('data-a="refund"','data-a="refund" data-ctx=\''+JSON.stringify({id:x.id,need:n.id})+'\'');}});
F('R-04',{tab:'S',kind:'sheet',base:'S-01',title:'Price change',r:function(){var s=cur().subs.filter(function(s){return s.name==='Prime Video';})[0];return '<p class="eyb">Subscription</p><h2>Prime Video now costs '+inr(349)+'. Hold the new price?</h2><p class="muted small">The extra comes from Food. You can stop tracking it instead.</p>'+
  btn('Hold the new price','subprice',{primary:true,v:s?s.id:''})+'<button class="link" data-a="substop" data-v="'+(s?s.id:'')+'">Stop tracking</button>';}});
F('R-05',{tab:'I',kind:'sheet',base:'I-01',title:'Late income',r:function(){return '<p class="eyb">Allowance</p><h2>Allowance is two days later than usual.</h2><p class="muted">Your jars keep their dots meanwhile. This happens; nothing needs fixing.</p>'+btn('Got it','late',{primary:true,v:'ok'})+'<button class="link" data-a="late" data-v="date">Change the usual date</button>';}});
F('R-06',{tab:'V',kind:'sheet',base:'V-03',title:'Withdraw',r:function(){var g=L.goals.filter(function(x){return x.id===S.ctx.g;})[0]||L.goals[0];var a=S.ctx.a||500;return '<p class="eyb">'+esc(g.name)+'</p><h2>Take '+inr(a)+' out of '+esc(g.name)+'?</h2><p class="muted">That is what savings are for. It goes into '+jarNames()[0]+'.</p>'+
  '<div class="row" style="gap:12px"><button class="chip" data-go="R-06" data-ctx=\''+JSON.stringify({g:g.id,a:Math.max(100,a-100)})+'\' aria-label="Less">− ₹100</button><button class="chip" data-go="R-06" data-ctx=\''+JSON.stringify({g:g.id,a:Math.min(g.saved,a+100)})+'\' aria-label="More">+ ₹100</button></div>'+btn('Take it out','withdraw',{primary:true}).replace('data-a="withdraw"','data-a="withdraw" data-ctx=\''+JSON.stringify({g:g.id,a:a})+'\'');}});
F('R-07',{tab:'H',kind:'push',title:'Notification shade',exempt:1,r:function(){var it=[['income','Trickle · Money arrived','₹9,000 came in from Allowance. Split it like last time?','Split it','I-04'],['subTomorrow','Trickle · Subscriptions','Google One renews tomorrow. Its money is already held.','See it','S-05'],['checkin','Trickle · Weekly check-in','A fuller week, mostly one dinner out.','Start the new week','N-05'],['story','Trickle · Month story','Your September story is ready.','Read it','N-04'],['welcome','Trickle · Welcome back','Your savings kept growing. Pick up from today.','Start from today','R-01']];
  return hd('Notification shade',{back:1})+'<main class="scr"><p class="muted small">Simulated Android shade. Each type has its own channel and one action.</p><div class="shadebox">'+it.map(function(n){return '<div class="ntf"><span class="nh">'+n[1].split(' · ')[0]+' · <span>'+n[1].split(' · ')[1]+'</span></span><b>'+n[2]+'</b><button class="na" data-a="nact" data-v="'+n[0]+'">'+n[3]+'</button></div>';}).join('')+'</div></main>';}});
F('R-08',{tab:'H',kind:'push',title:'Home-screen widgets',r:function(){var g=L.goals[0];return hd('Home-screen widgets',{back:1})+'<main class="scr"><p class="muted small">Android widgets, simulated. None show amounts.</p><div class="hs">'+
  '<div class="aw w41" aria-label="Pace widget, four by one"><span class="small">Trickle · '+paceWord()+'</span>'+glowTrack(timeFrac(),{label:'Pace'})+'</div>'+
  '<div class="aw w22" aria-label="Goal widget, two by two"><span class="small">'+esc(g.name)+'</span>'+dots(goalSegs(g),{size:'widget',zoomable:false})+'</div>'+
  '<button class="aw w21" data-go="P-01" aria-label="Pay widget, two by one" style="align-items:center;flex-direction:row;gap:8px">'+ic('pay','')+'<span>Scan to pay</span></button>'+
  '<div class="aw w22" aria-label="Jar widget, two by two, optional"><span class="small">Food · opt-in</span>'+dots([{amt:left('Food'),c:'j0',st:'solid',name:'Food left'}],{size:'widget',zoomable:false})+'</div></div></main>';}});

function approxW(n){if(n<=12)return wn(n);var d=Math.round(n/12);return d>12?'dozens':wn(d)+' dozen';}
