# theme, name, versions, value(question), v11 (Y/P/N), why dropped, cost L/M/H, rec, depth, reason, thumb
T=[]
def a(th,n,v,val,h,why,c,r,d,rs,tb=''):T.append(dict(th=th,n=n,v=v,val=val,h=h,why=why,c=c,r=r,d=d,rs=rs,tb=tb))
# TRACKING
a('Tracking','Linked UPI IDs (more than one)','2-10','Which of my UPI apps is tracked?','P','v11 has one ID, no "link another"','L','MUST','D','Most students use 2 apps (GPay + PhonePe); one ID misses spends')
a('Tracking','Manual spend entry ("Log cash")','2-10','How do I add a cash spend?','P','only a setup pad; Pay assumes UPI','L','MUST','G','Constraint: manual must be as fast as UPI; one button beside Pay')
a('Tracking','Manual-only tracking path','6-9','Can I use Trickle without linking UPI?','N','setup collapsed to 4 taps','M','MUST','D','Hard constraint says UPI or manual; both paths must exist')
a('Tracking','All spends list with filter chips','2,6,7,8,9','What did I actually buy?','N','cut to keep numbers off screens','M','MUST','E','Basic trust: people check a list before trusting a chart','v8tx')
a('Tracking','Spend detail (change jar, split, source)','6-9','Was this put in the right jar?','N','no list, so no detail','M','MUST','D','Wrong categories poison every insight')
a('Tracking','Sort an unknown UPI payment (top 3 guesses)','7,8,9','What was "PAYTM*QR7731"?','N','Actions tab removed','M','MUST','E','UPI merchant names are cryptic; one-tap guess keeps data clean')
a('Tracking','Remember payee to jar','7,8','Will it remember next time?','N','not rebuilt','L','MUST','D','Invisible default; reduces sorting to near zero')
a('Tracking','Recent spends on Home (size glyph)','2-10','Did that payment go through?','N','Home kept at 0 numbers','L','NICE','G','Reassurance; show 3 tile glyphs, amount on tap')
a('Tracking','Bank statement CSV/Excel import','7,8 (placeholder)','Can I bring my last month in?','N','never built','H','NICE','D','Fills week-1 empty state; complex mapping')
a('Tracking','UPI / Manual badge on rows','6,7','Where did this entry come from?','N','noise','L','NICE','D','Only in spend detail')
a('Tracking','Linkage diagram and source share bar','6,7','How much is auto-tracked?','N','numbers, low value','M','NO','-','Designer view, not a user question')
a('Tracking','Unknown credit question','11','Is this money in mine?','Y','','L','MUST','E','Kept')
a('Tracking','UPI AutoPay detection','11','Which charges repeat?','Y','','M','MUST','D','Kept (simulated)')
a('Tracking','Undo toast on money actions','7-11','Can I take that back?','Y','','L','MUST','G','Kept')
a('Tracking','Ledger invariant check','7-11','Are the numbers right?','Y','','M','MUST','D','Kept, internal')
# PAYING
a('Paying','Scan QR entry point','6,7,8','Pay a shop fast','P','Pay starts at "pick who"','L','MUST','G','The most common student payment; one tap from Pay')
a('Paying','Pay contact / bank transfer screens','6,7','Pay a friend or account','N','UPI app does this','M','NO','-','Hand-off to UPI app covers it')
a('Paying','Category tiles leave at pay','8-11','What does this cost my jar?','Y','','M','MUST','G','Core v11 moment')
a('Paying','Friction sheet with pace tick','2,6','Should I really buy this?','N','replaced by tiles leaving','M','NO','-','Tiles leaving is the friction')
a('Paying','"Food can cover this" line','8-11','Is there room?','Y','','L','MUST','G','Kept')
a('Paying','Empty jar: take from another jar','7,8,11','What if the jar is empty?','Y','','M','MUST','E','Kept (P-05)')
a('Paying','4-option cover sheet with slip line','7','Where should overspend come from?','N','29 numbers, panic','H','NO','-','One preselected choice replaced it')
a('Paying','"Next month starts a little lighter"','8,11','Can I borrow from next month?','Y','','L','MUST','E','Kept')
a('Paying','Repeat line "3rd time this week"','9,11','Am I doing this a lot?','Y','','L','MUST','G','Kept')
a('Paying','Round-up to savings at pay','6,7','Can small change save for me?','N','extra decision','M','NICE','D','Opt-in setting; Fi/Jupiter users like it; off by default')
a('Paying','Split at pay','7-11','Friends will pay me back','Y','','M','MUST','E','Kept')
a('Paying','Suggested jar at pay','8-11','Which jar?','Y','','L','MUST','G','Kept')
a('Paying','Live impact bullet on entry','6,7','How does this move my budget?','N','numbers','M','NO','-','Tiles leaving shows it')
a('Paying','Pre-pay interstitial (lo-fi)','Lo-fi','Pause before paying','N','superseded','M','NO','-','Superseded by tile moment')
# BUDGETING
a('Budgeting','Jar tile bars','8-11','How much is left per jar?','Y','','M','MUST','E','Kept')
a('Budgeting','Jar history (spends + weeks in jar detail)','4-7','Where did my Food money go?','P','M-02 shows tiles only','M','MUST','D','Answers "why is Food low" without a chart library','v6cat')
a('Budgeting','Category % cards on Home','7','Which jar is near empty?','N','75 numbers on Home','M','NO','-','Ostrich effect; budget stays off Home')
a('Budgeting','Safe to spend today','3-7','How much today?','N','number on Home caused panic','M','NICE','D','Only on tap inside Money, words first','v7home')
a('Budgeting','Budget runway "lasts till ~28th"','7','Will it last the month?','N','alarm framing','M','NICE','E','As words in jar detail: "Food lasts to about the 26th"','v7runway')
a('Budgeting','Pace projection bullet','5,6,7','Where will I end the month?','P','glow word only','M','NICE','D','Glow stays the glance; projection one tap deeper','v7pace')
a('Budgeting','Pace glow + word','8-11','Am I on track?','Y','','L','MUST','G','Kept')
a('Budgeting','Move tiles between jars','7,8,11','Shift money between jars','Y','','M','MUST','E','Kept')
a('Budgeting','Weekly period option','7,8,9','My allowance comes weekly','N','monthly-only build','M','MUST','D','Many students get weekly money; setting, not setup')
a('Budgeting','Payday-aligned period','7','Month starts on my payday','N','monthly-only build','M','NICE','D','Same setting as weekly')
a('Budgeting','Edit jars (add, rename, remove)','6-9','I spend on gym, not study','N','fixed by student type','M','MUST','D','Fixed jars break for real users')
a('Budgeting','Edit jar amount','6-9','Food needs more','P','only via move tiles','L','MUST','D','Direct edit is expected')
a('Budgeting','Copy last month\'s budget','7,11(notes)','Same as last month?','P','planned, not visible','L','MUST','D','Default at month start; zero effort')
a('Budgeting','Fill underfunded first','7','Top up the empty ones','N','jargon','L','NO','-','Auto-split already does it')
a('Budgeting','Fixed vs flexible meter','6,7','How much is committed?','P','hatched subs block','L','NO','-','Hatched block already shows it')
a('Budgeting','Red "Carried −₹240"','7','What did I overspend?','N','debt framing','L','NO','-','Never again (no red)')
a('Budgeting','Daily allowance number','2,6','Per-day budget','N','numbers','L','NO','-','Glow covers pace')
a('Budgeting','Gentle "jar nearly empty" nudge','6,7','Warn me before it runs out','N','alerts dropped with red','M','NICE','D','Opt-in, worded softly, ≤1/day')
a('Budgeting','Per-category rollover rules','7','Keep unused Food for next month','N','complexity','M','NO','-','Left over → savings is simpler')
# INCOME
a('Income','Auto-split with undo','8-11','Where does new money go?','Y','','M','MUST','E','Kept')
a('Income','Income sources list','7,8,9','Allowance, café shift, stipend','P','unknown-credit question only','M','MUST','E','Students juggle 2–3 sources')
a('Income','Income source mix chart','7','Which source matters most?','N','breadth','M','NO','-','A list answers it')
a('Income','Next money in (payday)','7','When does money come next?','N','not rebuilt','L','MUST','G','Calming fact, no budget number: "Allowance in 9 days"','v7payday')
a('Income','Expected vs received','7','Did it all arrive?','N','breadth','M','NO','-','Edge case')
a('Income','In vs out by week','7','Did I spend more than came in?','N','dense','M','NICE','D','Merged into month vs month','v7inout')
a('Income','"To assign" inbox','7','Money waiting for a job','N','jargon, chore','M','NO','-','Auto-split replaced it')
a('Income','New money sheet','8-11','Money landed','Y','','L','MUST','G','Kept (N-01)')
a('Income','Edit savings share of income','7,8,11(setup)','Save more from each payment','P','only in setup','L','MUST','D','Needs a later edit point')
a('Income','Total balance','2-11','How much do I have?','Y','','L','MUST','E','Kept (Money, one number)')
a('Income','Balance split bar','7,11','Where is it sitting?','Y','','L','MUST','E','Kept')
a('Income','Balance history area','7','How has it moved?','N','numbers','M','NO','-','Low action value')
a('Income','End-of-month forecast range','7','Where will I end up?','N','numbers, alarm','M','NICE','D','As tile range "likely / possible"','v7forecast')
a('Income','Moves log','7','What moved between jars?','N','breadth','L','NICE','D','Lives in All spends list')
# SAVINGS
a('Savings & goals','Goal tiles / waffle','7,8,9,11','How close is Goa?','Y','','M','MUST','E','Kept')
a('Savings & goals','Multiple goals','6-11','Goa and a laptop','Y','','L','MUST','E','Kept')
a('Savings & goals','Goal create with head start','6-11','Start a goal','Y','','L','MUST','E','Kept')
a('Savings & goals','Goal detail with contributions','6-9','What filled this goal?','P','rows only','M','MUST','D','Goal gradient needs a story of progress','v7goal')
a('Savings & goals','Goal ETA ("on track for Dec")','6,7,9','When will I get there?','N','not rebuilt','M','MUST','E','Strongest motivator; words + dot path','v7eta')
a('Savings & goals','Goal reached moment','6-11','I made it','Y','','L','MUST','G','Kept')
a('Savings & goals','Rainy-day jar','8,9','Money for surprises','P','merged into savings','L','NICE','E','Students value a buffer; one fixed goal')
a('Savings & goals','Savings rate waffle','7,9','What share did I keep?','N','library cut','L','NICE','E','Ratio, not ₹; pairs with story','v7rate')
a('Savings & goals','Savings growing by month','9','Am I saving more over time?','N','library cut','M','MUST','E','Peak-end: end the month on progress','v9w7')
a('Savings & goals','Contribution sources bar','6,7,9','What fills my savings?','N','breadth','M','NO','-','Goal detail list covers it')
a('Savings & goals','Withdrawals & slips','7','How often did I dip in?','N','guilt','M','NO','-','Guilt framing')
a('Savings & goals','Goal lock','7(question)','Stop me taking from Goa','N','never built','M','NICE','D','Asked for by Jupiter users; opt-in')
a('Savings & goals','Leftover swept chart','7','How much got saved at month end?','N','merged','L','NO','-','Savings growing shows it')
a('Savings & goals','Saved this month card','11','Did I save?','Y','','L','MUST','G','Kept')
a('Savings & goals','Quick add ₹100/₹500 to goal','8,9','Put a bit aside now','P','via move only','L','MUST','E','One-tap saving; matches tile unit')
a('Savings & goals','Goal milestones 25/50/75%','9(sound)','Small wins','N','not rebuilt','L','NICE','E','Goal gradient; chime + one line')
# SUBS
a('Subscriptions','Subscriptions list with due ring','3-11','What renews when?','Y','','M','MUST','E','Kept')
a('Subscriptions','"Next to come out" card','11','What leaves next?','Y','','L','MUST','G','Kept')
a('Subscriptions','Yearly cost (12-cell)','6,7','What does Spotify cost a year?','N','not rebuilt','L','MUST','E','The eye-opener behind cancelling','s6sub')
a('Subscriptions','Price change sheet','6,11','Netflix went up','Y','','L','MUST','E','Kept (N-02)')
a('Subscriptions','Price history line','6','How has it changed?','N','numbers','L','NO','-','Sheet covers it')
a('Subscriptions','Subscriptions calendar','6,7,9','Which days do they hit?','N','library cut','L','NICE','E','Month-so-far calendar can mark them')
a('Subscriptions','Renew reminder: Keep / I\'ll cancel','8','Cancel before it renews','P','stop tracking only','L','MUST','E','Real saving action, one day before')
a('Subscriptions','Add subscription (3 steps)','6,7,11','Track a new one','Y','','L','MUST','D','Kept')
a('Subscriptions','Subscription share donut','6','Which costs most?','N','donut ban','L','NO','-','List sorted by cost does it')
# SPLITS
a('Splits & owed','Friends owe you','7-11','Who owes me?','Y','','M','MUST','E','Kept')
a('Splits & owed','Remind (share message)','7,8,9','Nudge Arjun','P','button only','L','MUST','E','Copy/share text is the whole job')
a('Splits & owed','Paid back returns to jar','7,8,9,11','Where does repayment go?','Y','','M','MUST','D','Kept')
a('Splits & owed','Split later / pending split','7','Split this after dinner','N','not rebuilt','M','NICE','E','Common: bill paid, people sorted later')
a('Splits & owed','I owe others','Expl (Split)','Who do I owe?','N','never built','M','NICE','D','Completes the pair; outside budget')
a('Splits & owed','Group ledger app (Split concept)','Expl','Trip expenses','N','separate app','H','NO','-','Splitwise exists')
# REPEAT
a('Repeat buys','Little things Home card','9,11','What small things add up?','Y','','L','MUST','G','Kept')
a('Repeat buys','Repeat buys per place (×visits)','9','Where do I keep going?','P','2 rows only','L','MUST','E','Direct differentiator','v9w3')
a('Repeat buys','Repeat buys detail (₹ a year)','6,9','What does chai cost a year?','N','not rebuilt','M','MUST','E','Annualised cost changes behaviour','v9w2')
a('Repeat buys','"Skip 2 chais ≈ Goa 2 weeks sooner"','9','What if I cut back?','N','not rebuilt','L','MUST','E','Links habit to goal without guilt')
a('Repeat buys','How often (dot grid)','9','Which days?','N','library cut','L','NICE','D','Second-level detail')
a('Repeat buys','Trend word (fewer / more)','9','Is it growing?','N','library cut','L','NICE','E','One word, no chart')
a('Repeat buys','Repeat threshold 3×/4×/5×','9','What counts as repeat?','N','setting cut','L','NICE','D','Settings only')
a('Repeat buys','Accumulation 24h strip','6','When do I buy chai?','N','dense','M','NO','-','Low value')
# INSIGHTS
a('Insights & charts','Week vs last week','8,11','Better than last week?','Y','','L','MUST','G','Kept')
a('Insights & charts','Month-so-far calendar','3,7,9,11','Which days were heavy?','Y','','M','MUST','E','Kept')
a('Insights & charts','Where it went','5-11','What did I spend on?','Y','','L','MUST','E','Kept')
a('Insights & charts','Money flow (Sankey)','6,7,9,10,11','Where did all money go?','P','simplified to flow of tiles','H','NICE','D','v9 Sankey was the most-liked deep view','v9w0')
a('Insights & charts','Spend range per week','7,9,11(lib)','Steady or spiky?','P','library only','M','NICE','D','Keep in library','v9w4')
a('Insights & charts','This vs last month by jar','6,7,9','Which jar changed?','N','not rebuilt','M','MUST','E','The question users ask most after "where"','v9w5')
a('Insights & charts','Month by month (6 months)','4,6,7,9','Long view','N','not rebuilt','M','MUST','D','Needed once there is history','v7months')
a('Insights & charts','When you spend (time of day)','5,6,7,9','Evenings?','N','leaves tile','M','NICE','D','Library; words "mostly evenings"','v9w6')
a('Insights & charts','Weekday pattern','3,5,9','Weekends?','N','low value','M','NO','-','Calendar already shows it')
a('Insights & charts','Top places','6,7,9','Who gets most of my money?','N','not rebuilt','L','MUST','E','Big places, not only repeats','v7top')
a('Insights & charts','Purchase sizes histogram','6,7,9','Mostly small buys?','N','low value','M','NO','-','Low action value')
a('Insights & charts','Biggest buy this week','7','What was the big one?','N','breadth','L','NICE','E','One story card','v7big')
a('Insights & charts','"4 things changed" summary','7','What changed?','N','numbers','M','NICE','E','One sentence insight per week in check-in','v7four')
a('Insights & charts','Late-night buys','6,7','Do I spend at night?','N','breadth','L','NICE','E','One-line insight if true')
a('Insights & charts','Not-enough-data ghost state','7','Why is this empty?','N','not rebuilt','L','MUST','E','Week 1 needs honest empty states')
a('Insights & charts','Text insight cards (8)','2,5','Facts as text','N','text-heavy','L','NO','-','Rejected in v3')
a('Insights & charts','Radar / bubble / radial arcs / scatter','5,6','Chart variety','N','misleading','M','NO','-','Never again')
a('Insights & charts','Treemap','6, redesign','Share by area','N','dense','M','NO','-','Where it went covers it')
a('Insights & charts','Per-screen metaphors (road, iceberg…)','redesign','Emotional visuals','N','nothing learnable','H','NO','-','Never again','redesign')
a('Insights & charts','MoM sparklines','4','Trend at a glance','N','numbers','L','NO','-','Month by month replaces')
a('Insights & charts','Under-budget streak dots','6,7','Days in a row under','N','streak ban','L','NO','-','Never again (streaks)','v7streak')
a('Insights & charts','Overspend covers chart','7','What paid for overspend?','N','debt framing','L','NO','-','Never again')
a('Insights & charts','Heatmap + range strip','3,6','Hot days','P','calendar','M','NO','-','Month-so-far calendar replaced','v3ins')
# SETTINGS
a('Settings','Widget library: pin, reorder, hide','7,8,9,11(add only)','Make Home mine','P','add only, no reorder','M','NICE','E','Cap Home at 5 cards')
a('Settings','Per-widget ⚙ sheet','9','Tune a card','N','chrome','L','NO','-','Too much control')
a('Settings','Colour / B&W look','9,10,11','Calmer look','Y','','L','MUST','D','Kept')
a('Settings','Sounds on/off','9-11','Mute','Y','','L','MUST','D','Kept')
a('Settings','Less motion','8-11','Calmer motion','Y','','L','MUST','D','Kept')
a('Settings','Dark / light theme','2,11','Theme','Y','','L','MUST','D','Kept')
a('Settings','App PIN / lock','Lo-fi,6,7','Keep my money private','N','setup trimmed','M','MUST','D','Money app trust; offered after setup')
a('Settings','Permissions screen','6,7','What can Trickle see?','N','no SMS → little to ask','L','NO','-','Privacy line covers it')
a('Settings','Privacy line (local-first)','2-11','Is my data safe?','Y','','L','MUST','D','Kept')
a('Settings','Notification settings (caps, quiet hours)','Lo-fi,6,7,11(stated)','Control nudges','P','stated, not editable','L','MUST','D','Respect = retention')
a('Settings','Plain-words glossary / help','8','What is a tile?','P','key only','L','NICE','D','One sheet')
a('Settings','Prototype demo controls','8,9,11','Show a moment','Y','','L','NICE','D','Kept for testing')
# ONBOARDING
a('Onboarding','Splash with tiles','8-11','What is this?','Y','','L','MUST','G','Kept')
a('Onboarding','4-tap setup with student type','11','Get started fast','Y','','M','MUST','G','Kept')
a('Onboarding','Tile key taught once','9-11','What is ■?','Y','','L','MUST','G','Kept')
a('Onboarding','Allocation pie + 7 sliders','6,7','Plan every jar','N','54 numbers','H','NO','-','Never again')
a('Onboarding','Skip to demo','8,9,11','Look first','Y','','L','MUST','G','Kept')
a('Onboarding','First goal in setup','8','Save for something','N','one-decision rule','L','NICE','E','Offer after first week instead')
a('Onboarding','Period choice in setup','7,8','Weekly or monthly','N','extra step','L','NO','-','Settings, default monthly')
a('Onboarding','SMS permission screen','Lo-fi','Read SMS','N','constraint','M','NO','-','Hard constraint: never','onb_sms')
# RETENTION
a('Retention','Weekly check-in','8,9,11','How did the week go?','Y','','M','MUST','E','Kept')
a('Retention','Month story → fresh start','8,9,11','How did the month end?','Y','','M','MUST','E','Kept')
a('Retention','Repeat buys card in check-in','9','Little things last week','N','not rebuilt','L','MUST','E','Ties the differentiator to the weekly loop')
a('Retention','Story card "Biggest buy" / "Little things pour"','9','Month highlights','P','5 cards, fewer types','L','NICE','E','Variety keeps the story fresh')
a('Retention','Savings / income sounds','9,11','Feel the win','Y','','L','MUST','G','Kept')
a('Retention','One "for you" card (sort, settle, renew)','7,8,9','What needs me?','N','inbox removed','M','NICE','G','At most one, no badge, no count')
a('Retention','"N things need you" badge','7','To-do list','N','anxiety','L','NO','-','Never again')
a('Retention','Streaks / points','6,7','Gamification','N','what-the-hell effect','L','NO','-','Never again')
