/* ===== Trickle v8 — rhythm: Monday check-in, period story, drawer, onboarding ===== */
A.checkin=function(){S.drawer=false;sheet('checkin',{i:0});};
SHEETS.checkin=function(){var s=S.sheet,g=topGoal(),w0=NOW-7*DAY,b='',prog='<div class="prog">'+[0,1,2].map(function(i){return '<i class="'+(i<=s.i?'on':'')+'"></i>';}).join('')+'</div>';
 if(s.i===0){var a=[];CATS.forEach(function(c){var v=0;TX.forEach(function(t){if(t.type==='spend'&&t.cat===c&&t.ts>w0&&t.ts<=NOW&&!t.goalFunded)v+=t.amt;});a=a.concat(rep(Math.round(v/TILE),{c:catColor(c),cls:'pop'}));});a.forEach(function(x,i){x.d=i*40;});
  b='<span class="lbl">Last week</span><h1>Here’s where last week went.</h1>'+tg(a,8,24,6)+legend(CATS)+'<p class="muted">Each tile is ₹100. Tap them for the total.</p>';}
 if(s.i===1){var sv=0;TX.forEach(function(t){if(t.type==='transfer'&&t.ts>monthStart(NOW)&&t.dst.some(function(x){return x.ref.indexOf('goal:')===0&&x.ref!=='goal:general';})&&t.reason!=='headstart')sv+=t.amt;});
  b='<span class="lbl">Savings</span><h1>'+esc(g.name)+' is '+goalWords(g)+'.</h1><div style="display:flex;justify-content:center">'+waffle(g,20,{highlight:Math.round(sv/g.target*100)})+'</div><p class="muted">The glowing tiles were added this '+'month.</p>';}
 if(s.i===2){var big=CATS.slice().sort(function(x,y){return spentMonth(y)-spentMonth(x);})[0];
  b='<span class="lbl">This week</span><h1>'+big+' is the busy one. Keep an eye on it?</h1>'+tg(catSpecs(big).specs,12,18,5)+'<p class="muted">No rules to set. We’ll show you '+big+'’s tiles when you pay.</p>';}
 return '<div class="story" role="dialog" aria-modal="true" data-sheet="checkin">'+prog+'<div class="sh" style="justify-content:flex-end;display:flex;padding:8px 12px"><button class="iconbtn" data-a="close" aria-label="Close">'+ic('close')+'</button></div><div class="sb">'+b+'</div><div class="sf" style="padding:14px 18px 18px">'+(s.i<2?'<button class="btn" data-a="cinext">Next</button>':'<button class="btn" data-a="cidone">Sounds good</button>')+'</div></div>';};
A.cinext=function(){S.sheet.i++;render();};
A.cidone=function(){S.checkinDone=true;S.sheet=null;var g=topGoal();toast(esc(g.name)+' is '+goalWords(g)+'. See you next Monday.');render();};
/* ---------- period-end story ---------- */
A.story=function(){S.drawer=false;sheet('story',{i:0});};
function leftoverNow(){var p=POOLS(),t=0;CATS.forEach(function(c){if((p.b[c]||0)>.5)t+=Math.round(p.b[c]);});return t;}
SHEETS.story=function(){var s=S.sheet,g=topGoal(),m=new Date(NOW).getMonth(),b='',n=4,prog='<div class="prog">'+[0,1,2,3].map(function(i){return '<i class="'+(i<=s.i?'on':'')+'"></i>';}).join('')+'</div>';
 if(s.i===0){var a=[];CATS.forEach(function(c){a=a.concat(rep(Math.round(spentMonth(c)/TILE),{c:catColor(c)}));});b='<span class="lbl">'+MONL[m]+' in tiles</span><h1>This is everything you spent.</h1>'+tg(a.slice(0,120),12,16,4,{attr:'data-a="reveal" data-v="'+fmt(spentMonth())+'"'})+legend(CATS);}
 if(s.i===1){var sm=TX.filter(function(t){return t.type==='spend'&&inMonth(t,NOW)&&t.amt<100;}),tot=sm.reduce(function(x,t){return x+t.amt;},0);b='<span class="lbl">Small spends</span><h1>Chai, xerox, metro. They add up.</h1>'+tg(sm.map(function(t){return {c:catColor(t.cat)};}),10,14,4)+'<p class="muted">One tile per spend under ₹100. Together about '+fmt(Math.round(tot/50)*50)+'.</p>';}
 if(s.i===2){var lo=leftoverNow();b='<span class="lbl">Leftover</span><h1>'+(lo?'What’s left '+(SWEEP==='auto'?'goes to '+esc(g.name)+'.':'waits for you to decide.'):'Everything got used. That’s fine too.')+'</h1>'+tg(rep(Math.round(lo/TILE),{c:'var(--save)',cls:'pop'}).map(function(x,i){x.d=i*50;return x;}),10,16,4)+'<p class="muted">'+nextPeriodWord()+' starts fresh with a full budget'+(CATS.some(function(c){return (POOLS().b[c]||0)<-.5;})?', a little lighter where you went over.':'.')+'</p>';}
 if(s.i===3){var sv=savedIn(m)+leftoverNow()*(SWEEP==='auto'?1:0);b='<div class="moment">'+waffle(g,18)+'<span class="lbl">'+MONL[m]+'</span><p class="big">You saved '+fmt(sv)+'.</p><p class="muted">'+esc(g.name)+' is '+goalWords(g)+'.</p></div>';}
 return '<div class="story" role="dialog" aria-modal="true" data-sheet="story">'+prog+'<div class="sh" style="justify-content:flex-end;display:flex;padding:8px 12px"><button class="iconbtn" data-a="close" aria-label="Close">'+ic('close')+'</button></div><div class="sb">'+b+'</div><div class="sf" style="padding:14px 18px 18px">'+(s.i<n-1?'<button class="btn" data-a="stnext">Next</button>':'<button class="btn" data-a="fresh">'+(PERIOD==='week'?'Start the new week':'Start '+nextPeriodWord())+'</button>')+'</div></div>';};
A.stnext=function(){S.sheet.i++;render();};
/* fresh start: sweep leftover, move clock to the new period, allowance arrives and auto-splits */
A.fresh=function(){var p=POOLS(),parts=[],g=topGoal(),name=thisPeriodName();CATS.forEach(function(c){if((p.b[c]||0)>.5)parts.push({ref:'budget:'+c,amt:Math.round(p.b[c]*100)/100});});
 var tot=parts.reduce(function(a,x){return a+x.amt;},0),end=periodEnd();
 if(tot>0){if(SWEEP==='auto')xfer(end-60e3,parts,saveDst(tot),'sweep',{auto:true,period:name});else{xfer(end-60e3,parts,[{ref:'new_money',amt:tot}],'sweep',{auto:false,period:name});S.pendingLeft={amt:tot,name:name};}}
 NOW=end+9*3600e3;S.checkinDone=false;var r={save:0,goal:g};
 var inc=null;if(new Date(NOW).getDate()===1){inc=push({type:'income',ts:NOW,amt:ALLOW,merchant:'Allowance',from:'Amma & Appa',source:'UPI',account:UPI_IDS[0],incomeCat:'Allowance'});r=autoSplit(inc);}
 FORCE_PACE=null;S.sheet=null;S.tab='home';S.fresh=true;setTimeout(function(){S.fresh=false;},1600);
 if(inc){S.sheet={k:'incconf',id:inc.id,fill:r.fill,save:r.save,goal:r.goal.id,amt:ALLOW,name:thisPeriodName()+' allowance',fresh:1};S.after=runIncome;}else toast(thisPeriodName()+' starts fresh.',null,5000);render();};
/* ---------- drawer ---------- */
function drawerHTML(){var budget=Object.keys(FIXED).reduce(function(a,c){return a+FIXED[c];},0);
 return '<aside class="drawer" role="dialog" aria-label="Settings"><div class="sh" style="display:flex;align-items:center;gap:10px;padding:14px"><span class="avatar">T</span><b style="flex:1">Tarun</b><button class="iconbtn" data-a="drawer" data-x="0" aria-label="Close settings">'+ic('close')+'</button></div><div class="sb" style="flex:1;overflow-y:auto;padding:0 14px 20px">'+
 '<span class="lbl">Tracking</span>'+(TRACK==='upi'?UPI_IDS.map(function(u){return '<div class="set">'+ic('link')+'<span class="t">'+u+'<small>Linked UPI ID · spends appear by themselves</small></span></div>';}).join('')+'<button class="set" data-a="linkmore">'+ic('plus')+'<span class="t">Link another UPI ID</span></button>':'<div class="set">'+ic('pen')+'<span class="t">Manual entry<small>You add spends with Log cash</small></span></div><button class="set" data-a="linkmore">'+ic('link')+'<span class="t">Link a UPI ID instead</span></button>')+
 '<button class="set" data-a="import">'+ic('upload')+'<span class="t">Import a bank statement<small>Coming soon</small></span></button>'+
 '<span class="lbl" style="margin-top:14px;display:block">Budget</span><div class="set" style="cursor:default"><span class="t">Budget period</span><div class="seg"><button data-a="period" data-x="week" aria-pressed="'+(PERIOD==='week')+'">Weekly</button><button data-a="period" data-x="month" aria-pressed="'+(PERIOD==='month')+'">Monthly</button></div></div>'+
 '<div class="set" style="cursor:default"><span class="t">Fixed budget<small>'+fmt(budget)+' a month</small></span><button class="iconbtn" data-a="bud" data-x="-500" aria-label="Lower budget">−</button><button class="iconbtn" data-a="bud" data-x="500" aria-label="Raise budget">+</button></div>'+
 '<div class="set" style="cursor:default"><span class="t">Categories<small>'+CATS.join(', ')+'</small></span></div>'+
 '<div class="set" style="cursor:default"><span class="t">Leftover at '+periodWord()+' end</span><div class="seg"><button data-a="sweep" data-x="auto" aria-pressed="'+(SWEEP==='auto')+'">Auto</button><button data-a="sweep" data-x="manual" aria-pressed="'+(SWEEP==='manual')+'">Ask me</button></div></div>'+
 '<div class="set" style="cursor:default"><span class="t">Reduce motion</span><div class="seg"><button data-a="rm" data-x="0" aria-pressed="'+!S.reduced+'">Off</button><button data-a="rm" data-x="1" aria-pressed="'+S.reduced+'">On</button></div></div>'+
 '<button class="set" data-a="replay">'+ic('back')+'<span class="t">Replay onboarding</span></button>'+
 '<span class="lbl" style="margin-top:14px;display:block">Prototype controls</span>'+
 '<div class="set" style="cursor:default"><span class="t">Glow</span><div class="seg"><button data-a="fp" data-x="" aria-pressed="'+!FORCE_PACE+'">Real</button><button data-a="fp" data-x="ok" aria-pressed="'+(FORCE_PACE==='ok')+'">Calm</button><button data-a="fp" data-x="fast" aria-pressed="'+(FORCE_PACE==='fast')+'">Fast</button></div></div>'+
 '<button class="set" data-a="cafe">'+ic('plus')+'<span class="t">Café shift pay arrives</span></button>'+
 '<button class="set" data-a="checkin">'+ic('cal')+'<span class="t">Open Monday check-in</span></button>'+
 '<button class="set" data-a="story">'+ic('moon')+'<span class="t">End this '+periodWord()+' (story)</span></button>'+
 '</div></aside>';}
A.period=function(x){PERIOD=x;render();};
A.bud=function(x){var tot=Object.keys(FIXED).reduce(function(a,c){return a+FIXED[c];},0),nt=Math.max(2000,tot+(+x));CATS.forEach(function(c){FIXED[c]=Math.round(FIXED[c]/tot*nt/100)*100;});render();};
A.rm=function(x){S.reduced=x==='1';render();};
A.fp=function(x){FORCE_PACE=x||null;render();};
A.import=function(){toast('Statement import is coming soon. Upload a PDF or CSV from your bank here.');render();};
A.linkmore=function(){if(TRACK!=='upi'){TRACK='upi';}else if(UPI_IDS.indexOf('tarun@ybl')<0)UPI_IDS.push('tarun@ybl');toast('UPI ID linked. New spends will appear by themselves.');render();};
A.replay=function(){S.drawer=false;S.onb=1;S.od={track:null,period:'month',budget:6000,cats:['Food','Travel','Fun','Essentials'],goal:'Goa trip'};render();};
/* ---------- onboarding ---------- */
function onbScreen(){var o=S.od,st=S.onb,b='',f='',dots='';var total=8;
 dots='<div class="steps" aria-label="Step '+st+' of '+total+'">';for(var i=1;i<=total;i++)dots+='<i class="'+(i<=st?'on':'')+'"></i>';dots+='</div>';
 var head='<div class="sh" style="display:flex;align-items:center;gap:8px;padding:14px 12px 0">'+(st>1&&st<8?'<button class="iconbtn" data-a="ob" data-x="'+(st===4&&o.track==='manual'?3:st-1)+'" aria-label="Back">'+ic('back')+'</button>':'<span style="width:44px"></span>')+dots+'<span style="width:44px"></span></div>';
 if(st===1){var a=[];for(var k=0;k<36;k++)a.push({c:k<22?['var(--food)','var(--travel)','var(--fun)','var(--ess)'][k%4]:'var(--save)',cls:'pop',d:k*30});a.forEach(function(x){x.cls='pop';});
  b='<div class="moment" style="padding-top:40px">'+tg(a,6,30,7,{center:1,attr:'id="welcome"'})+'<h1>Money as tiles.</h1><p class="muted" style="max-width:30ch">Spend some, save the rest. Trickle shows it without a wall of numbers.</p></div>';f='<button class="btn" data-a="ob" data-x="2">Start</button><button class="btn ghost" data-a="skip">Skip, show me the demo</button>';}
 if(st===2){b='<h1>How should Trickle see your spends?</h1><button class="opt def" data-a="obt" data-x="upi">'+ic('link')+'<span class="t"><b>Link my UPI ID</b><small>Spends show up by themselves</small></span></button><button class="opt" data-a="obt" data-x="manual">'+ic('pen')+'<span class="t"><b>I’ll add them myself</b><small>Two taps per spend</small></span></button><p class="faint" style="font-size:12.5px">You can import a bank statement later from settings.</p>';}
 if(st===3&&o.track==='upi'){b='<h1>Link your UPI ID</h1><p class="muted">We only read payments made from this ID.</p><label class="lbl" for="upiid">UPI ID</label><input class="fld" id="upiid" value="tarun@oksbi" autocomplete="off">';f='<button class="btn" data-a="oblink">Link it</button>';}
 if(st===3&&o.track==='manual'){b='<h1>Adding a spend takes two taps.</h1><div class="stage">'+tg(rep(3,{c:'var(--food)',cls:'pop'}),3,34,8,{center:1})+'<p class="muted">Amount, then what it was for.</p></div><button class="opt" data-a="import">'+ic('upload')+'<span class="t"><b>Import a bank statement</b><small>Coming soon</small></span></button>';f='<button class="btn" data-a="ob" data-x="4">Sounds good</button>';}
 if(st===4){b='<h1>How often do you get money?</h1><p class="muted">Your budget follows it, and so does the glow on Home.</p><button class="opt" data-a="obp" data-x="week">'+ic('cal')+'<span class="t"><b>Every week</b><small>Pocket money, weekly pay</small></span></button><button class="opt def" data-a="obp" data-x="month">'+ic('cal')+'<span class="t"><b>Every month</b><small>Allowance, stipend</small></span></button>';}
 if(st===5){var n=o.budget/BIG;b='<h1>How much do you want to spend each month?</h1><p class="muted">Rent and fees aside. Each tile is ₹500.</p><div class="stage">'+tg(rep(n,{c:'var(--fillg)'}),6,26,6,{center:1})+'<div class="amt-big" style="font-size:40px;min-height:0">'+fmt(o.budget)+'</div><div style="display:flex;gap:12px"><button class="iconbtn" data-a="obb" data-x="-500" aria-label="Less">−</button><button class="iconbtn" data-a="obb" data-x="500" aria-label="More">+</button></div></div>';f='<button class="btn" data-a="ob" data-x="6">That’s my budget</button>';}
 if(st===6){var all=['Food','Travel','Fun','Essentials','Laundry','Books'];b='<h1>What do you usually spend on?</h1><p class="muted">We split your budget across these. Change it any time.</p><div class="chips">'+all.map(function(c){return '<button class="chip" data-a="obc" data-x="'+c+'" aria-pressed="'+(o.cats.indexOf(c)>=0)+'"><span class="cdot" style="background:'+catColor(c)+'"></span>'+c+'</button>';}).join('')+'</div><div class="stage" style="min-height:0">'+tg(obFixedSpecs(),12,16,4,{center:1})+'</div>';f='<button class="btn" data-a="ob" data-x="7"'+(o.cats.length?'':' disabled style="opacity:.4"')+'>Next</button>';}
 if(st===7){b='<h1>What’s your first thing to save for?</h1><p class="muted">We’ll give it a head start.</p>'+[['Goa trip','sun'],['New phone','spark'],['Rainy day','jar'],['Concert','music']].map(function(x){return '<button class="opt'+(x[0]==='Goa trip'?' def':'')+'" data-a="obg" data-x="'+x[0]+'">'+ic(x[1])+'<span class="t"><b>'+x[0]+'</b></span></button>';}).join('');}
 if(st===8){var nb=o.budget/BIG,ns=(ALLOW-o.budget)/BIG;b='<h1>Here’s your '+(o.period==='week'?'first week':'allowance')+', sorted.</h1><div class="stage incstage">'+tg(rep(ALLOW/BIG,{c:'var(--bone)'}),9,18,5,{center:1,attr:'id="inctiles"'})+'<div class="split3"><div>'+tg(rep(nb,{}),6,18,5,{attr:'id="incb"'})+'<div class="lab">Budget</div></div><div>'+tg(rep(Math.max(1,ns),{}),Math.min(6,Math.max(1,ns)),18,5,{attr:'id="incs"'})+'<div class="lab">'+esc(o.goal)+'</div></div></div></div><p class="big" style="font-family:var(--display);font-size:26px">'+fmt(ALLOW-o.budget)+' went to '+esc(o.goal)+'.</p><p class="muted">Budget fills first, the rest is saved. Every month, by itself.</p>';f='<button class="btn" data-a="obdone">Open Trickle</button>';}
 return '<div data-screen="onb'+st+(st===3?o.track:'')+'" style="min-height:100%;display:flex;flex-direction:column">'+head+'<div class="scr" style="flex:1;min-height:0">'+b+'</div>'+(f?'<div class="sf" style="padding:12px 18px 18px;display:flex;flex-direction:column;gap:8px">'+f+'</div>':'')+'</div>';}
function obFixedSpecs(){var o=S.od,ws=o.cats.reduce(function(a,c){return a+CAT_DEF[c].w;},0),sp=[];o.cats.forEach(function(c){sp=sp.concat(rep(Math.round(o.budget*CAT_DEF[c].w/ws/TILE),{c:catColor(c)}));});return sp;}
A.ob=function(x){S.onb=+x;if(S.onb===8){S.sheet=null;S.after=function(){S.sheet={fill:S.od.budget};runIncome();S.sheet=null;};}render();};
A.obt=function(x){S.od.track=x;A.ob(3);};
A.oblink=function(){var v=(document.getElementById('upiid').value||'').trim();if(!/^[\w.\-]+@[\w]+$/.test(v)){toast('That doesn’t look like a UPI ID. It should look like name@bank.');render();return;}S.od.upi=v;A.ob(4);};
A.obp=function(x){S.od.period=x;A.ob(5);};
A.obb=function(x){S.od.budget=Math.min(8500,Math.max(2000,S.od.budget+(+x)));render();};
A.obc=function(c){var a=S.od.cats,i=a.indexOf(c);if(i>=0)a.splice(i,1);else a.push(c);render();};
A.obg=function(x){S.od.goal=x;A.ob(8);};
A.obdone=function(){var o=S.od;TRACK=o.track||'upi';PERIOD=o.period;if(o.upi)UPI_IDS=[o.upi];
 CATS=o.cats.slice();var ws=CATS.reduce(function(a,c){return a+CAT_DEF[c].w;},0);FIXED={};var acc=0;CATS.forEach(function(c,i){var v=i===CATS.length-1?o.budget-acc:Math.round(o.budget*CAT_DEF[c].w/ws/100)*100;FIXED[c]=v;acc+=v;});
 seedLedger({goalName:o.goal});S.onb=null;S.tab='home';S.fresh=true;setTimeout(function(){S.fresh=false;},1600);render();};
A.skip=function(){S.od.track='upi';A.obdone();};
