/* ===== Trickle v12 — frames part 2: Income, Spending ===== */
function setLinks(list){return '<p class="eyb" style="margin-top:8px">More settings</p><div class="card list">'+list.map(function(x){return li({t:x[1],go:x[0]});}).join('')+'</div>';}
/* ---------- Income ---------- */
var I_SET=[['I-S1','Sources'],['I-S2','Savings share'],['I-S3','Split order'],['I-S4','Period']];
F('I-01',{tab:'I',kind:'tab',title:'Income',r:function(){var m=cur(),ni=nextIncome(),last=m.incomes.filter(function(i){return i.intent==='split';}).slice(-1)[0];
  var sp=last&&last.split?last.split:{save:m.savingsSplit,budget:m.budget};
  return hd('Income',{help:'I-00',gear:'I-S1'})+'<main class="scr">'+
  '<section class="card"><p class="eyb">Next money in</p><p class="lead">'+(ni?esc(ni.src.name)+' · '+ni.label:'No regular income yet')+'</p>'+(ni?glowTrack(1-ni.days/31,{label:'How close the next money is'})+'<p class="sub">The glow moves closer each day.</p>':'')+'</section>'+
  '<button class="card tile" data-go="I-03" data-ctx=\'{"id":"'+(last?last.id:'')+'"}\' aria-label="This split"><p class="eyb">This split</p>'+dots([{amt:sp.save,c:'sv',st:'solid',name:'Savings'}],{zoomable:false})+'<p class="sub">Savings, taken first</p>'+dots([{amt:sp.budget,c:'inc',st:'solid',name:'Budget'}],{zoomable:false})+'<p class="sub">Budget for jars and subscriptions</p></button>'+
  '<section class="card"><p class="eyb">Sources</p><div class="list">'+L.sources.map(function(s,i){return li({t:esc(s.name),s:s.kind==='regular'?'Regular':'Now and then',go:'I-02',ctx:{i:i}});}).join('')+'</div></section>'+
  '<section class="card"><p class="eyb">Where money sits</p>'+dots([{amt:leftAll(),c:'inc',st:'solid',name:'In jars'},{amt:subsHeld(),c:'inc',st:'held',name:'Held'}])+'<p class="sub">Jars, plus dashed money held for subscriptions</p>'+
   dots([{amt:savingsTotal(),c:'sv',st:'solid',name:'Savings'}])+'<p class="sub">Savings</p>'+(owedOpen()?dots([{amt:owedOpen(),c:'inc',st:'owed',name:'Owed to you'}])+'<p class="sub">Owed by friends · not counted as yours yet</p>':'')+'</section>'+key()+
  '<section class="card dash"><p class="eyb">Demo</p><p class="sub">Simulate money arriving from a linked UPI ID.</p><div class="chips"><button class="chip" data-go="I-04">Allowance arrives</button><button class="chip" data-go="I-05">A friend sends money</button></div></section></main>';}});
F('I-02',{tab:'I',kind:'push',title:'Source',r:function(){var s=L.sources[S.ctx.i||0];var ks=monthKeys();var pays=[];ks.forEach(function(k){L.months[k].incomes.forEach(function(i){if(i.src===s.name)pays.push({k:k,i:i});});});
  return hd(s.name,{back:1})+'<main class="scr"><section class="card"><p class="eyb">Usual day</p><p class="lead">'+(s.day?'The '+ord(s.day):'No fixed day')+'</p>'+(s.from?'<p class="sub">From '+esc(s.from)+'</p>':'')+'</section>'+
  '<section class="card"><p class="eyb">Paydays</p><div class="list">'+pays.reverse().map(function(p){var mo=+p.k.slice(5)-1;var late=s.day&&p.i.day>s.day;return li({t:MONL[mo],s:late?'A little later than usual':p.i.intent==='later'?'Kept for later':'On the usual day',go:'I-03',ctx:{id:p.i.id}});}).join('')+'</div></section></main>';}});
F('I-03',{tab:'I',kind:'push',title:'Payday',r:function(){var inc=null,mk_=null;monthKeys().forEach(function(k){L.months[k].incomes.forEach(function(i){if(i.id===S.ctx.id){inc=i;mk_=k;}});});if(!inc){inc=cur().incomes[0];mk_=curKey();}
  var mo=+mk_.slice(5)-1;var sp=inc.split||(inc.intent==='split'?{save:L.months[mk_].savingsSplit,budget:L.months[mk_].budget}:null);var open=inc.ts&&UNDO.length&&inc.id===S.lastIncome;
  return hd(MONL[mo]+' '+inc.src,{back:1})+'<main class="scr"><section class="card"><p class="eyb">Came in</p>'+dots([{amt:inc.amt,c:'inc',st:'solid',name:'Came in'}])+'</section>'+
  (sp?'<section class="card"><p class="eyb">Where it went</p>'+dots([{amt:sp.save,c:'sv',st:'solid',name:'Savings'}])+'<p class="sub">Savings</p>'+dots([{amt:sp.budget,c:'inc',st:'solid',name:'Budget'}])+'<p class="sub">Budget</p></section>':'<section class="card"><p class="sub">Kept for later, in general savings.</p></section>')+key()+
  (S.lastIncome===inc.id?btn('Undo this split','undo',{}):'<p class="small muted">Undo is open right after a split. To move money now, use jar settings in Spending.</p>')+'</main>';}});
F('I-04',{tab:'I',kind:'sheet',base:'I-01',title:'New money',r:function(){var amt=9000,sv=Math.round(amt*L.saveShare/100/100)*100;
  return '<p class="eyb">Allowance · '+esc(L.upiIds.filter(function(u){return u.linked;}).map(function(u){return u.id;})[0]||'manual')+'</p><h2>'+inr(amt)+' came in. Split it like last time?</h2>'+
  '<div class="sv-drop">'+dots([{amt:sv,c:'sv',st:'solid',name:'Savings'}],{zoomable:false})+'</div><p class="small muted">Savings first</p>'+dots([{amt:amt-sv,c:'inc',st:'solid',name:'Jars'}],{zoomable:false})+'<p class="small muted">Into your jars, same shares</p>'+key()+
  btn('Split it','incsplit',{primary:true})+'<button class="link" data-go="I-S2">Change the savings share</button>';},after:function(){fx('savings.drop',document.querySelector('.sv-drop'));}});
F('I-05',{tab:'I',kind:'sheet',base:'I-01',title:'Irregular money',r:function(){var pick=S.ctx.pick||'owed';var ow=L.owed.filter(function(o){return o.friend==='Arjun'&&o.back<o.amt;})[0];
  return '<p class="eyb">From Arjun</p><h2>'+inr(300)+' came in. What is it for?</h2><div class="choice" role="radiogroup" aria-label="What is it for">'+[['month','For this month','Goes into your jars'],['later','Keep for later','Goes to general savings'],['owed','Friend paying back','Settles what Arjun owes'+(ow?'':' (nothing open)')]].map(function(o){return '<button class="opt'+(pick===o[0]?' def':'')+'" role="radio" aria-checked="'+(pick===o[0])+'" data-a="irrpick" data-v="'+o[0]+'"><span class="grow"><b>'+o[1]+'</b><small>'+o[2]+'</small></span></button>';}).join('')+'</div>'+btn('Done','irrdone',{primary:true});}});
F('I-S1',{tab:'I',kind:'push',title:'Sources',r:function(){return hd('Sources',{back:1})+'<main class="scr"><div class="card list">'+L.sources.map(function(s,i){return li({t:esc(s.name),s:(s.kind==='regular'?'Regular':'Now and then')+(s.day?' · usually the '+ord(s.day):''),go:'I-02',ctx:{i:i}});}).join('')+'</div>'+
  '<p class="eyb">Add a source</p><label class="sr" for="srcname">Source name</label><input class="inp" id="srcname" placeholder="Scholarship, stipend, tutoring…"><div class="chips" role="group" aria-label="Kind"><button class="chip" data-a="srcadd" data-v="regular">Add as regular</button><button class="chip" data-a="srcadd" data-v="irregular">Add as now and then</button></div>'+setLinks(I_SET.slice(1))+'</main>';}});
F('I-S2',{tab:'I',kind:'push',title:'Savings share',r:function(){var p=S.ctx.p==null?L.saveShare:S.ctx.p;var sv=Math.round(9000*p/100/100)*100;
  return hd('Savings share',{back:1})+'<main class="scr"><p class="muted">Taken first from each regular income.</p><p class="amtv">'+p+'%</p><div class="row" style="justify-content:center;gap:12px"><button class="chip" data-a="sharestep" data-v="-5" aria-label="Less">−</button><button class="chip" data-a="sharestep" data-v="5" aria-label="More">+</button></div>'+
  '<section class="card">'+dots([{amt:sv,c:'sv',st:'solid',name:'Savings'},{amt:9000-sv,c:'inc',st:'solid',name:'Budget'}],{zoomable:false})+'<p class="sub">Next allowance, split this way</p></section>'+key()+btn('Save','sharesave',{primary:true,v:p})+setLinks([I_SET[0],I_SET[2],I_SET[3]])+'</main>';}});
F('I-S3',{tab:'I',kind:'push',title:'Split order',r:function(){return hd('Split order',{back:1})+'<main class="scr"><p class="muted">Savings from each split fill goals in this order.</p><div class="card list">'+L.goals.map(function(g,i){return '<div class="li"><span class="t"><b>'+esc(g.name)+'</b><small>'+(i===0?'Fills first':'Then')+'</small></span><button class="ib" data-a="gup" data-v="'+g.id+'" aria-label="Move '+esc(g.name)+' up">'+ic('up')+'</button></div>';}).join('')+'</div>'+setLinks([I_SET[0],I_SET[1],I_SET[3]])+'</main>';}});
F('I-S4',{tab:'I',kind:'push',title:'Period',r:function(){return hd('Period',{back:1})+'<main class="scr"><p class="muted">How long one budget lasts.</p><div class="choice" role="radiogroup">'+[['week','Week','Resets each Monday'],['month','Month','Resets on the first'],['payday','Payday to payday','Resets when allowance arrives']].map(function(o){return '<button class="opt'+(L.period===o[0]?' def':'')+'" role="radio" aria-checked="'+(L.period===o[0])+'" data-a="period" data-v="'+o[0]+'"><span class="grow"><b>'+o[1]+'</b><small>'+o[2]+'</small></span></button>';}).join('')+'</div>'+setLinks(I_SET.slice(0,3))+'</main>';}});

/* ---------- Spending ---------- */
var S_SET=[['S-S1','Jars'],['S-S3','Move dots between jars'],['S-S4','Copy last month'],['S-S5','Subscriptions'],['S-S6','Remember payees'],['S-S7','Import a statement']];
function laneCard(){var t=L.today,m=cur(),dow=new Date(t.y,t.m,t.d).getDay();var mon=t.d-((dow+6)%7);var per=Math.floor(leftAll()/daysLeft());var rows=[];
  for(var i=0;i<7;i++){var d=mon+i;if(d<1||d>dim(t.y,t.m))continue;var name=DOW[new Date(t.y,t.m,d).getDay()];var seg;
    if(d<t.d){var s=0;m.spends.forEach(function(x){if(x.day===d)s+=x.amt;});seg=[{amt:s,c:'ink',st:'out',name:name+' spent'}];}
    else if(d===t.d){var s2=0;m.spends.forEach(function(x){if(x.day===d)s2+=x.amt;});seg=[{amt:Math.max(0,per-s2),c:'ink',st:'solid',name:'Today left'},{amt:s2,c:'ink',st:'out',name:'Today spent'}];}
    else seg=[{amt:per,c:'ink',st:'solid',name:name}];
    rows.push('<div class="lane'+(d===t.d?' today':'')+'"><span class="lb">'+(d===t.d?'Today':name)+'</span><span class="bar">'+dots(seg,{size:'widget',cols:22,zoomable:false})+'</span></div>');}
  return '<section class="card" aria-label="Day lanes"><p class="eyb">This week, day by day</p><div class="lanes">'+rows.join('')+'</div><p class="sub">Past days show what went. Days ahead share what is left evenly; if a day runs long, the rest re-spread.</p></section>';}
F('S-01',{tab:'S',kind:'tab',title:'Spending',r:function(){var m=cur(),per=Math.floor(leftAll()/daysLeft());var held=liveSubs(m).filter(function(s){return s.state==='held';}).sort(function(a,b){return a.due-b.due;});var rp=topRepeat();var rc=rp?repeatCount(rp,7):0;
  return hd('Spending',{help:'S-00',gear:'S-S1'})+'<main class="scr"><p class="lead">'+inr(per)+' a day for the rest of '+MONL[L.today.m]+'</p>'+laneCard()+
  '<div class="row"><p class="eyb grow">Jars</p><button class="link small" data-go="S-02">All spends</button></div><div class="grid">'+jarNames().map(function(j){var ex=S.exp===j;
    return '<section class="card'+(ex?' wide':'')+'" aria-label="'+j+'"><button class="row" style="width:100%;min-height:44px" data-a="expand" data-v="'+j+'" aria-expanded="'+ex+'"><span class="jarname grow">'+jsw(j)+j+'</span><span class="chev">'+ic(ex?'up':'down','')+'</span></button>'+dots(jarSegs(j))+
    (ex?'<div class="row" style="margin-top:6px"><span class="grow small muted">'+inr(left(j))+' left · '+inr(daySpread(j))+' a day</span><button class="chip" data-go="S-03" data-ctx=\'{"j":"'+j+'"}\'>Open '+j+'</button></div>':'')+'</section>';}).join('')+'</div>'+legendLS()+
  '<section class="card" aria-label="Held for subscriptions"><p class="eyb">Held for subscriptions</p>'+dots([{amt:subsHeld(),c:'inc',st:'held',name:'Held'}])+'<div class="list">'+held.map(function(s){return li({t:esc(s.name),s:s.due-L.today.d===1?'Due tomorrow':'Due later this month',go:'S-05',ctx:{id:s.id}});}).join('')+'</div></section>'+
  '<section class="card" aria-label="Owed to you"><p class="eyb">Owed to you</p>'+(owedOpen()?dots([{amt:owedOpen(),c:'inc',st:'owed',name:'Owed'}])+'<p class="sub">Outside your balance until they pay</p><div class="list">'+L.owed.filter(function(o){return o.back<o.amt;}).map(function(o){return li({t:o.friend,s:esc(o.what),go:'S-06',ctx:{id:o.id}});}).join('')+'</div>':'<p class="sub">Nobody owes you right now.</p>')+'</section>'+
  (rp?'<section class="card" aria-label="Repeat buys"><p class="eyb">Repeat buys</p><p><b>'+esc(rp)+'</b></p><p class="sub">'+ordw(rc)+' '+((L.payees[rp]||{}).thing||'buy').replace(/s$/,'')+' this week · they add up in Insights</p></section>':'')+key()+'</main>';}});
F('S-02',{tab:'S',kind:'push',title:'All spends',exempt:1,r:function(){var c=S.ctx,m=cur();var list=m.spends.slice().reverse().filter(function(x){return (!c.jar||x.jar===c.jar)&&(!c.src||x.src===c.src)&&(!c.wk||x.day>L.today.d-7);});
  function ch(k,v,l){var on=c[k]===v;var n=Object.assign({},c);if(on)delete n[k];else n[k]=v;return '<button class="chip" data-go="S-02" data-ctx=\''+JSON.stringify(n)+'\' aria-pressed="'+on+'">'+l+'</button>';}
  return hd('All spends',{back:1})+'<main class="scr"><div class="chips" role="group" aria-label="Filters">'+jarNames().map(function(j){return ch('jar',j,jsw(j)+j);}).join('')+ch('src','upi','UPI')+ch('src','cash','Cash')+ch('wk',1,'This week')+'</div>'+
  '<div class="card list">'+(list.length?list.map(function(x){return li({lead:jsw(x.jar),t:esc(x.payee),s:dd(x.day)+' · '+(x.src==='cash'?'Cash':'UPI')+(x.sorted===false?' · not sorted':'')+(x.refund?' · refunded':''),r:inr(x.amt),go:'S-04',ctx:{id:x.id}});}).join(''):'<p class="sub">No spends match these filters.</p>')+'</div></main>';}});
F('S-03',{tab:'S',kind:'push',title:'Jar',r:function(){var j=S.ctx.j||'Food',m=cur();var g=ghost(j);var sp=jarSpent(j);var extra=g!=null?sp-g:0;
  var segs=[{amt:left(j),c:jcls(j),pat:jpat(j),st:'solid',name:j+' left'},{amt:extra>0?g:sp,c:jcls(j),st:'out',name:'Spent'}];if(extra>0)segs.push({amt:extra,c:jcls(j),st:'hatch',name:'More than last month by now'});
  var recent=m.spends.filter(function(x){return x.jar===j;}).slice(-5).reverse();
  return hd(j,{back:1})+'<main class="scr"><section class="card"><p class="eyb">This month</p>'+dots(segs)+'<p class="legend"><span>'+dot1(jcls(j),'solid')+' left</span><span>'+dot1(jcls(j),'out')+' spent</span>'+(extra>0?'<span>'+dot1('ink','hatch')+' more than last month by now</span>':'')+'</p></section>'+
  (g!=null?'<section class="card"><p class="eyb">Last month by this date</p>'+dots([{amt:g,c:'ink',st:'ghost',name:'Last month'}])+'<p class="sub">'+(extra>0?'A little more than last month so far. The days ahead re-spread to match.':'Less than last month so far.')+'</p></section>':'')+
  '<div class="chips"><button class="chip" data-go="S-S3" data-ctx=\'{"from":"'+j+'"}\'>Move dots</button><button class="chip" data-go="S-S2" data-ctx=\'{"j":"'+j+'"}\'>Change amount</button></div>'+key()+
  '<p class="eyb">Recent</p><div class="card list">'+recent.map(function(x){return li({t:esc(x.payee),s:relDay(x.day),r:dots([{amt:x.amt,c:jcls(j),st:'out',name:x.payee}],{size:'widget',zoomable:false}),go:'S-04',ctx:{id:x.id}});}).join('')+'</div></main>';}});
F('S-04',{tab:'S',kind:'push',title:'Spend',r:function(){var x=findSpend(S.ctx.id)||cur().spends[0];var spl=S.ctx.split;var sel=S.ctx.sel||[];
  var body='<section class="card"><p class="eyb">'+dd(x.day)+' · '+(x.src==='cash'?'Cash':'UPI')+'</p><p class="big">'+inr(x.amt)+'</p>'+(x.split?'<p class="sub">Split with '+x.split.friends.map(function(f){return f.name;}).join(', ')+'</p>':'')+(x.refund?'<p class="sub">Refunded to '+x.jar+'</p>':'')+'</section>';
  if(spl&&!x.split){body+='<section class="card"><p class="eyb">Split equally with</p><div class="chips" role="group" aria-label="Friends">'+['Arjun','Meera','Kiran','Rohan'].map(function(f){return '<button class="chip" data-a="s4f" data-v="'+f+'" aria-pressed="'+(sel.indexOf(f)>=0)+'">'+f+'</button>';}).join('')+'</div>'+btn('Split it','s4split',{primary:true})+'</section>';}
  else body+='<p class="eyb">Jar</p><div class="chips" role="group" aria-label="Change jar">'+jarNames().map(function(j){return '<button class="chip" data-a="s4jar" data-v="'+j+'" aria-pressed="'+(x.jar===j)+'">'+jsw(j)+j+'</button>';}).join('')+'</div>'+(x.split?'':'<button class="btn block" data-go="S-04" data-ctx=\''+JSON.stringify({id:x.id,split:1})+'\'>Split with friends</button>');
  return hd(esc(x.payee),{back:1})+'<main class="scr">'+body+'</main>';}});
F('S-05',{tab:'S',kind:'push',title:'Subscription',r:function(){var s=cur().subs.filter(function(s){return s.id===S.ctx.id;})[0]||cur().subs[1];
  return hd(esc(s.name),{back:1})+'<main class="scr"><section class="card"><p class="eyb">A year of '+esc(s.name)+'</p>'+dots([{amt:s.amt*12,c:'inc',st:s.state==='held'?'held':'out',name:'A year'}])+'<p class="sub">'+(s.state==='held'?'Held until the '+ord(s.due):s.ended?'Not tracked from next month':'Paid this month')+'</p></section>'+key()+
  '<div class="choice"><button class="opt def" data-a="back"><span class="grow"><b>Keep it</b><small>Trickle keeps holding it each month</small></span></button><button class="opt" data-a="subremind" data-v="'+s.id+'"><span class="grow"><b>'+(s.cancelRemind?'Reminder set':'Remind me to cancel')+'</b><small>A note the day before it renews</small></span></button><button class="opt" data-a="substop" data-v="'+s.id+'"><span class="grow"><b>Stop tracking</b><small>Held money goes back to '+jarNames()[0]+'</small></span></button></div></main>';}});
F('S-06',{tab:'S',kind:'push',title:'Friend',r:function(){var o=L.owed.filter(function(o){return o.id===S.ctx.id;})[0]||L.owed[0];var due=o.amt-o.back;var link='upi://pay?pa='+L.upi+'&pn=Tarun&am='+due+'&tn='+encodeURIComponent(o.what);
  return hd(o.friend,{back:1})+'<main class="scr"><section class="card"><p class="eyb">'+esc(o.what)+'</p>'+dots([{amt:o.back,c:'inc',st:'solid',name:'Paid back'},{amt:due,c:'inc',st:'owed',name:'Owed'}])+'<p class="sub">'+(due?'Dashed dots are still owed. They fill in when '+o.friend+' pays.':'All paid back.')+'</p></section>'+key()+
  (due?btn('Remind '+o.friend,'remind',{primary:true,v:o.id})+(S.ctx.share?'<section class="card" aria-label="Share message"><p class="eyb">Message to send</p><p class="small" style="user-select:all">Hey '+o.friend+', your share for '+esc(o.what)+' is '+inr(due)+'. Pay here: '+esc(link)+'</p><button class="chip" data-a="copy" data-v="'+esc(link)+'">Copy link</button></section>':'')+
   '<button class="link" data-a="paidback" data-v="'+o.id+'">'+o.friend+' paid me back</button>':'')+'</main>';}});
F('S-07',{tab:'S',kind:'sheet',base:'S-01',title:'Sort payment',r:function(){var n=L.needs.filter(function(n){return n.kind==='sort';})[0];var x=n?findSpend(n.ref):null;if(!x)return '<h2>Everything is sorted</h2>'+btn('Close','back',{primary:true});
  var g=guessJars(x);return '<p class="eyb">Sort payment</p><h2>'+inr(x.amt)+' to '+esc(x.payee)+'. Which jar?</h2><div class="chips" role="group" aria-label="Pick a jar">'+g.map(function(j){return '<button class="chip" data-a="sortjar" data-v="'+j+'" data-ctx=\''+JSON.stringify({id:x.id,need:n.id,rem:S.ctx.rem!==false})+'\'>'+jsw(j)+j+'</button>';}).join('')+'</div>'+
  '<div class="row"><span class="grow small">Remember this payee</span><button class="tog" role="switch" aria-checked="'+(S.ctx.rem!==false)+'" data-a="remtog" aria-label="Remember this payee"></button></div>';}});
F('S-S1',{tab:'S',kind:'push',title:'Jars',r:function(){return hd('Jars',{back:1})+'<main class="scr"><div class="card list">'+jarNames().map(function(j){return li({lead:jsw(j),t:j,s:jpat(j)?'Patterned, so it stays distinct':'',go:'S-S2',ctx:{j:j}});}).join('')+'</div>'+
  '<label class="sr" for="jarname">New jar name</label><input class="inp" id="jarname" placeholder="New jar name"><button class="btn block" data-a="addjar">Add a jar</button>'+(S.ctx.err?'<p class="small" role="alert">'+esc(S.ctx.err)+'</p>':'')+setLinks(S_SET.slice(1))+'</main>';}});
F('S-S2',{tab:'S',kind:'push',title:'Jar amount',r:function(){var j=S.ctx.j||'Food',m=cur();var v=S.ctx.v==null?m.jars[j].budget:S.ctx.v;var diff=v-m.jars[j].budget;
  var src=jarNames().filter(function(x){return x!==j;}).sort(function(a,b){return left(b)-left(a);})[0];
  return hd(j,{back:1})+'<main class="scr"><p class="muted">Amount for this month</p><p class="amtv">'+inr(v)+'</p><div class="row" style="justify-content:center;gap:12px"><button class="chip" data-a="jstep" data-v="-100" aria-label="Less by one hundred">− ₹100</button><button class="chip" data-a="jstep" data-v="100" aria-label="More by one hundred">+ ₹100</button></div>'+
  '<p class="small muted" style="text-align:center">'+(diff>0?'Comes from '+src:diff<0?'Goes to '+src:'Your budget stays the same; the change moves between jars.')+'</p>'+btn('Save','jsave',{primary:true})+
  '<details class="card"><summary class="small" style="min-height:44px;display:flex;align-items:center">Rename or remove</summary><label class="sr" for="jren">New name</label><input class="inp" id="jren" placeholder="New name for '+j+'"><div class="chips"><button class="chip" data-a="jrename">Rename</button><button class="chip" data-a="jremove">Remove jar</button></div>'+(S.ctx.err?'<p class="small" role="alert">'+esc(S.ctx.err)+'</p>':'')+'</details></main>';}});
F('S-S3',{tab:'S',kind:'push',title:'Move dots',r:function(){var c=S.ctx;var from=c.from||'Food';var to=c.to;var amt=c.amt||100;
  return hd('Move dots',{back:1})+'<main class="scr"><p class="muted">From '+from+'</p>'+dots([{amt:left(from),c:jcls(from),pat:jpat(from),st:'solid',name:from+' left'}])+
  '<p class="eyb">To</p><div class="chips" role="group" aria-label="To jar">'+jarNames().filter(function(x){return x!==from;}).map(function(x){return '<button class="chip" data-a="mvto" data-v="'+x+'" aria-pressed="'+(x===to)+'">'+jsw(x)+x+'</button>';}).join('')+'</div>'+
  '<p class="amtv">'+inr(amt)+'</p><div class="row" style="justify-content:center;gap:12px"><button class="chip" data-a="mvstep" data-v="-100" aria-label="Less">− ₹100</button><button class="chip" data-a="mvstep" data-v="100" aria-label="More">+ ₹100</button></div>'+
  btn(to?'Move to '+to:'Pick a jar','mvgo',{primary:true})+key()+'</main>';}});
F('S-S4',{tab:'S',kind:'push',title:'Copy last month',r:function(){var pk=prevKey();var pm=L.months[pk];var mo=+pk.slice(5)-1;
  return hd('Copy last month',{back:1})+'<main class="scr"><p class="muted">Use '+MONL[mo]+'’s jar amounts for '+MONL[L.today.m]+'. Your budget stays the same.</p><section class="card">'+Object.keys(pm.jars).map(function(j){return '<p class="small jarname">'+jsw(j)+j+'</p>'+dots([{amt:pm.jars[j].budget,c:pm.jars[j].c,pat:pm.jars[j].pat,st:'solid',name:j}],{size:'widget'});}).join('')+'</section>'+btn('Copy '+MONL[mo]+'’s jars','copylast',{primary:true})+key()+'</main>';}});
F('S-S5',{tab:'S',kind:'push',title:'Subscriptions',r:function(){var m=cur();var step=S.ctx.add;
  if(step){return hd('Add a subscription',{back:1})+'<main class="scr"><div class="choice">'+[['Netflix',199,10],['YouTube Premium',129,18],['Swiggy One',75,25],['JioCinema',29,12]].map(function(s){return '<button class="opt" data-a="subadd" data-v=\''+JSON.stringify(s)+'\'><span class="grow"><b>'+s[0]+'</b><small>Hold '+inr(s[1])+' each month</small></span></button>';}).join('')+'</div></main>';}
  return hd('Subscriptions',{back:1})+'<main class="scr"><p class="muted">Trickle holds each price inside your budget and pays it on the due day.</p><div class="card list">'+m.subs.filter(function(s){return s.state!=='stopped';}).map(function(s){return li({t:esc(s.name),s:s.state==='held'?'Held':'Paid',r:inr(s.amt),go:'S-05',ctx:{id:s.id}});}).join('')+'</div>'+
  '<button class="btn block" data-go="S-S5" data-ctx=\'{"add":1}\'>Add a subscription</button>'+setLinks([S_SET[0],S_SET[4]])+'</main>';}});
F('S-S6',{tab:'S',kind:'push',title:'Remember payees',r:function(){var ps=Object.keys(L.payees);return hd('Remember payees',{back:1})+'<main class="scr"><p class="muted">Payments to these go straight to their jar.</p><div class="card list">'+ps.map(function(p){return '<div class="li"><span class="t"><b>'+esc(p)+'</b></span><span class="chips">'+jarNames().slice(0,4).map(function(j){return '<button class="chip" style="padding:0 10px" data-a="payeejar" data-v="'+j+'" data-ctx=\''+JSON.stringify({p:p})+'\' aria-pressed="'+(L.payees[p].jar===j)+'" aria-label="'+esc(p)+' to '+j+'">'+jsw(j)+'</button>';}).join('')+'</span></div>';}).join('')+'</div></main>';}});
F('S-S7',{tab:'S',kind:'push',title:'Import a statement',r:function(){return hd('Import a statement',{back:1})+'<main class="scr"><section class="card"><p class="lead">Coming later</p><p class="sub">You will be able to add a bank statement file to fill in older spends. For now, link a UPI ID or log spends by hand.</p><button class="btn block" disabled aria-disabled="true" style="opacity:.5">Choose file</button></section></main>';}});
